Doxygen: NavPathElemContext Class Reference
NavPathElemContext Class Reference
#include <context.h>
Classes
class Private
Public Member Functions
virtual TemplateVariant get (const char *name) const
Gets the value for a field name.
virtual int addRef ()
Increase object's reference count.
virtual int release ()
Decreases object's reference count, destroy object if 0.
Public Member Functions inherited from RefCountedContext
RefCountedContext (const char *)
virtual ~RefCountedContext ()
int addRef ()
int release ()
Public Member Functions inherited from TemplateStructIntf
virtual ~TemplateStructIntf ()
Destroys the struct.
Static Public Member Functions
static NavPathElemContext * alloc (const Definition *def)
Private Member Functions
NavPathElemContext (const Definition *def)
~NavPathElemContext ()
Private Attributes
Private * p
Detailed Description
Definition at line 886 of file context.h.
Constructor & Destructor Documentation
NavPathElemContext()
NavPathElemContext::NavPathElemContext (const Definition * def) private
Definition at line 7818 of file context.cpp.
References p, and Private.
Referenced by alloc().
~NavPathElemContext()
NavPathElemContext::~NavPathElemContext () private
Definition at line 7823 of file context.cpp.
References p.
Member Function Documentation
addRef()
virtual int NavPathElemContext::addRef () inline virtual
Increase object's reference count.
Implements TemplateStructIntf.
Definition at line 893 of file context.h.
References RefCountedContext::addRef().
alloc()
static NavPathElemContext* NavPathElemContext::alloc (const Definition * def) inline static
Definition at line 889 of file context.h.
References NavPathElemContext().
Referenced by DefinitionContext< FileContext::Private >::fillPath().
get()
TemplateVariant NavPathElemContext::get (const char * name) const virtual
Gets the value for a field name.
Parameters
[in] name The name of the field.
Implements TemplateStructIntf.
Definition at line 7828 of file context.cpp.
References NavPathElemContext::Private::get(), and p.
release()
virtual int NavPathElemContext::release () inline virtual
Decreases object's reference count, destroy object if 0.
Implements TemplateStructIntf.
Definition at line 894 of file context.h.
References RefCountedContext::release().
Member Data Documentation
p
Private* NavPathElemContext::p private
Definition at line 900 of file context.h.
Referenced by get(), NavPathElemContext(), and ~NavPathElemContext().
The documentation for this class was generated from the following files:
src/context.h
src/context.cpp