Doxygen: MemberListContext::Private Class Reference
MemberListContext::Private Class Reference
Public Member Functions
void addMember (MemberDef *md)
Public Member Functions inherited from GenericNodeListContext
GenericNodeListContext ()
uint count () const
Returns the number of elements in the list.
TemplateVariant at (uint index) const
Returns the element at index position index.
TemplateListIntf::ConstIterator * createIterator () const
Creates a new iterator for this list.
void append (const TemplateVariant &ctn)
bool isEmpty () const
int addRef ()
Increase object's reference count.
int release ()
Decreases object's reference count, destroy object if 0.
Public Member Functions inherited from TemplateListIntf
virtual ~TemplateListIntf ()
Destroys the list.
Additional Inherited Members
Static Public Member Functions inherited from GenericNodeListContext
static GenericNodeListContext * alloc ()
Detailed Description
Definition at line 8581 of file context.cpp.
Member Function Documentation
addMember()
void MemberListContext::Private::addMember (MemberDef * md) inline
Definition at line 8584 of file context.cpp.
References MemberContext::alloc(), and GenericNodeListContext::append().
Referenced by MemberListContext::MemberListContext().
The documentation for this class was generated from the following file:
src/context.cpp