Doxygen: SectionManager Class Reference
SectionManager Class Reference
singleton class that owns the list of all sections
#include <section.h>
Public Member Functions
SectionInfo * add (const SectionInfo &si)
Add a new section given the data of an existing section.
SectionInfo * add (const char *label, const char *fileName, int lineNr, const char *title, SectionType type, int level, const char *ref=0)
Add a new section Return a non-owning pointer to the newly added section.
Public Member Functions inherited from LinkedMap< SectionInfo >
const SectionInfo * find (const char *k) const
Find an object given the key.
SectionInfo * find (const char *key)
A non-const wrapper for find() const.
SectionInfo * add (const char *k, Args &&... args)
Adds a new object to the ordered set if it was not added already.
bool del (const char *k)
Removes an object from the container and deletes it.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
bool empty () const
size_t size () const
void clear ()
Static Public Member Functions
static SectionManager & instance ()
returns a reference to the singleton
Private Member Functions
SectionManager ()
SectionManager (const SectionManager &other)=delete
SectionManager & operator= (const SectionManager &other)=delete
Additional Inherited Members
Public Types inherited from LinkedMap< SectionInfo >
using Ptr = std::unique_ptr< SectionInfo >
using Vec = std::vector< Ptr >
using Map = std::unordered_map< std::string, SectionInfo * >
using iterator = typename Vec::iterator
using const_iterator = typename Vec::const_iterator
Detailed Description
singleton class that owns the list of all sections
Definition at line 127 of file section.h.
Constructor & Destructor Documentation
SectionManager() [1/2]
SectionManager::SectionManager () inline private
Definition at line 153 of file section.h.
SectionManager() [2/2]
SectionManager::SectionManager (const SectionManager & other) private delete
Member Function Documentation
add() [1/2]
SectionInfo* SectionManager::add (const char * label, const char * fileName, int lineNr, const char * title, SectionType type, int level, const char * ref = 0) inline
Add a new section Return a non-owning pointer to the newly added section.
Definition at line 139 of file section.h.
References LinkedMap< T >::add().
add() [2/2]
SectionInfo* SectionManager::add (const SectionInfo & si) inline
Add a new section given the data of an existing section.
Returns a non-owning pointer to the newly added section.
Definition at line 132 of file section.h.
References LinkedMap< T >::add(), SectionInfo::fileName(), SectionInfo::label(), SectionInfo::level(), SectionInfo::lineNr(), SectionInfo::ref(), SectionInfo::title(), and SectionInfo::type().
Referenced by TagFileParser::addDocAnchors(), addRelatedPage(), DefinitionImpl::addSectionsToDefinition(), and findMainPage().
instance()
static SectionManager& SectionManager::instance () inline static
returns a reference to the singleton
Definition at line 146 of file section.h.
Referenced by TagFileParser::addDocAnchors(), addRelatedPage(), DefinitionImpl::addSectionsToDefinition(), cleanUpDoxygen(), clearAll(), DocAnchor::DocAnchor(), DocHtmlCaption::DocHtmlCaption(), DocRef::DocRef(), findMainPage(), PerlModGenerator::generatePerlModForPage(), generateXMLForPage(), DocSection::parse(), DocSecRefItem::parse(), DocRoot::parse(), resolveLink(), resolveUserReferences(), PageDefImpl::writeDocumentation(), writeGroupTreeNode(), GroupDefImpl::writePageDocumentation(), and PageDefImpl::writePageDocumentation().
operator=()
SectionManager& SectionManager::operator= (const SectionManager & other) private delete
The documentation for this class was generated from the following file:
src/section.h