Doxygen: OutputList Class Reference
OutputList Class Reference
Class representing a list of output generators that are written to in parallel.
#include <outputlist.h>
Public Member Functions
OutputList ()
OutputList (const OutputList &ol)
OutputList & operator= (const OutputList &ol)
virtual ~OutputList ()
template<class Generator >
void add ()
size_t size () const
void disableAllBut (OutputGenerator::OutputType o)
void enableAll ()
void disableAll ()
void disable (OutputGenerator::OutputType o)
void enable (OutputGenerator::OutputType o)
bool isEnabled (OutputGenerator::OutputType o)
void pushGeneratorState ()
void popGeneratorState ()
void generateDoc (const char *fileName, int startLine, const Definition *ctx, const MemberDef *md, const QCString &docStr, bool indexWords, bool isExample, const char *exampleName, bool singleLine, bool linkFromIndex, bool markdownSupport)
void writeDoc (DocRoot *root, const Definition *ctx, const MemberDef *md)
void parseText (const QCString &textStr)
void startIndexSection (IndexSections is)
void endIndexSection (IndexSections is)
void writePageLink (const char *name, bool first)
void startProjectNumber ()
void endProjectNumber ()
void writeStyleInfo (int part)
void startFile (const char *name, const char *manName, const char *title)
void writeSearchInfo ()
void writeFooter (const char *navPath)
void endFile ()
void startTitleHead (const char *fileName)
void endTitleHead (const char *fileName, const char *name)
void startTitle ()
void endTitle ()
void startParagraph (const char *classDef=0)
void endParagraph ()
void writeString (const char *text)
void startIndexListItem ()
void endIndexListItem ()
void startIndexList ()
void endIndexList ()
void startIndexKey ()
void endIndexKey ()
void startIndexValue (bool b)
void endIndexValue (const char *name, bool b)
void startItemList ()
void endItemList ()
void startIndexItem (const char *ref, const char *file)
void endIndexItem (const char *ref, const char *file)
void docify (const char *s)
void codify (const char *s)
void writeObjectLink (const char *ref, const char *file, const char *anchor, const char *name)
void writeCodeLink (const char *ref, const char *file, const char *anchor, const char *name, const char *tooltip)
void writeTooltip (const char *id, const DocLinkInfo &docInfo, const char *decl, const char *desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)
void startTextLink (const char *file, const char *anchor)
void endTextLink ()
void startHtmlLink (const char *url)
void endHtmlLink ()
void writeStartAnnoItem (const char *type, const char *file, const char *path, const char *name)
void writeEndAnnoItem (const char *name)
void startTypewriter ()
void endTypewriter ()
void startGroupHeader (int extraLevels=0)
void endGroupHeader (int extraLevels=0)
void startItemListItem ()
void endItemListItem ()
void startMemberSections ()
void endMemberSections ()
void startHeaderSection ()
void endHeaderSection ()
void startMemberHeader (const char *anchor, int typ=2)
void endMemberHeader ()
void startMemberSubtitle ()
void endMemberSubtitle ()
void startMemberDocList ()
void endMemberDocList ()
void startMemberList ()
void endMemberList ()
void startInlineHeader ()
void endInlineHeader ()
void startAnonTypeScope (int i1)
void endAnonTypeScope (int i1)
void startMemberItem (const char *anchor, int i1, const char *id=0)
void endMemberItem ()
void startMemberTemplateParams ()
void endMemberTemplateParams (const char *anchor, const char *inheritId)
void startMemberGroupHeader (bool b)
void endMemberGroupHeader ()
void startMemberGroupDocs ()
void endMemberGroupDocs ()
void startMemberGroup ()
void endMemberGroup (bool last)
void insertMemberAlign (bool templ=FALSE)
void insertMemberAlignLeft (int typ=0, bool templ=FALSE)
void writeRuler ()
void writeAnchor (const char *fileName, const char *name)
void startCodeFragment (const char *style)
void endCodeFragment (const char *style)
void startCodeLine (bool hasLineNumbers)
void endCodeLine ()
void writeLineNumber (const char *ref, const char *file, const char *anchor, int lineNumber)
void startEmphasis ()
void endEmphasis ()
void writeChar (char c)
void startMemberDoc (const char *clName, const char *memName, const char *anchor, const char *title, int memCount, int memTotal, bool showInline)
void endMemberDoc (bool hasArgs)
void startDoxyAnchor (const char *fName, const char *manName, const char *anchor, const char *name, const char *args)
void endDoxyAnchor (const char *fn, const char *anchor)
void writeLatexSpacing ()
void startDescription ()
void endDescription ()
void startDescItem ()
void endDescItem ()
void startDescForItem ()
void endDescForItem ()
void startSubsection ()
void endSubsection ()
void startSubsubsection ()
void endSubsubsection ()
void startCenter ()
void endCenter ()
void startSmall ()
void endSmall ()
void lineBreak (const char *style=0)
void startBold ()
void endBold ()
void startMemberDescription (const char *anchor, const char *inheritId=0, bool typ=false)
void endMemberDescription ()
void startMemberDeclaration ()
void endMemberDeclaration (const char *anchor, const char *inheritId)
void writeInheritedSectionTitle (const char *id, const char *ref, const char *file, const char *anchor, const char *title, const char *name)
void startExamples ()
void endExamples ()
void startParamList (ParamListTypes t, const char *title)
void endParamList ()
void startIndent ()
void endIndent ()
void startSection (const char *lab, const char *title, SectionType t)
void endSection (const char *lab, SectionType t)
void addIndexItem (const char *s1, const char *s2)
void writeSynopsis ()
void startClassDiagram ()
void endClassDiagram (const ClassDiagram &d, const char *f, const char *n)
void startPageRef ()
void endPageRef (const char *c, const char *a)
void startQuickIndices ()
void endQuickIndices ()
void writeSplitBar (const char *name)
void writeNavigationPath (const char *s)
void writeLogo ()
void writeQuickLinks (bool compact, HighlightedItem hli, const char *file)
void writeSummaryLink (const char *file, const char *anchor, const char *title, bool first)
void startContents ()
void endContents ()
void startPageDoc (const char *pageTitle)
void endPageDoc ()
void writeNonBreakableSpace (int num)
void startDescTable (const char *title)
void endDescTable ()
void startDescTableRow ()
void endDescTableRow ()
void startDescTableTitle ()
void endDescTableTitle ()
void startDescTableData ()
void endDescTableData ()
void startDotGraph ()
void endDotGraph (DotClassGraph &g)
void startInclDepGraph ()
void endInclDepGraph (DotInclDepGraph &g)
void startCallGraph ()
void endCallGraph (DotCallGraph &g)
void startDirDepGraph ()
void endDirDepGraph (DotDirDeps &g)
void startGroupCollaboration ()
void endGroupCollaboration (DotGroupCollaboration &g)
void writeGraphicalHierarchy (DotGfxHierarchyTable &g)
void startTextBlock (bool dense=FALSE)
void endTextBlock (bool paraBreak=FALSE)
void lastIndexPage ()
void startMemberDocPrefixItem ()
void endMemberDocPrefixItem ()
void startMemberDocName (bool align)
void endMemberDocName ()
void startParameterType (bool first, const char *key)
void endParameterType ()
void startParameterName (bool one)
void endParameterName (bool last, bool one, bool bracket)
void startParameterList (bool openBracket)
void endParameterList ()
void exceptionEntry (const char *prefix, bool closeBracket)
void startConstraintList (const char *header)
void startConstraintParam ()
void endConstraintParam ()
void startConstraintType ()
void endConstraintType ()
void startConstraintDocs ()
void endConstraintDocs ()
void endConstraintList ()
void startMemberDocSimple (bool b)
void endMemberDocSimple (bool b)
void startInlineMemberType ()
void endInlineMemberType ()
void startInlineMemberName ()
void endInlineMemberName ()
void startInlineMemberDoc ()
void endInlineMemberDoc ()
void startLabels ()
void writeLabel (const char *l, bool isLast)
void endLabels ()
void startFontClass (const char *c)
void endFontClass ()
void writeCodeAnchor (const char *name)
void setCurrentDoc (const Definition *context, const char *anchor, bool isSourceFile)
void addWord (const char *word, bool hiPriority)
void startPlainFile (const char *name)
void endPlainFile ()
Public Member Functions inherited from OutputDocInterface
virtual ~OutputDocInterface ()
Public Member Functions inherited from BaseOutputDocInterface
virtual ~BaseOutputDocInterface ()
Public Member Functions inherited from CodeOutputInterface
virtual ~CodeOutputInterface ()
Private Member Functions
void debug ()
void clear ()
template<typename T , class... Ts, class... As>
void forall (void(T::*methodPtr)(Ts...), As &&... args)
Private Attributes
std::vector< std::unique_ptr< OutputGenerator > > m_outputs
Additional Inherited Members
Public Types inherited from BaseOutputDocInterface
enum ParamListTypes { Param, RetVal, Exception }
enum SectionTypes { EnumValues, Examples }
Detailed Description
Class representing a list of output generators that are written to in parallel.
Definition at line 37 of file outputlist.h.
Constructor & Destructor Documentation
OutputList() [1/2]
OutputList::OutputList ()
Definition at line 34 of file outputlist.cpp.
OutputList() [2/2]
OutputList::OutputList (const OutputList & ol)
Definition at line 39 of file outputlist.cpp.
References m_outputs.
~OutputList()
OutputList::~OutputList () virtual
Definition at line 59 of file outputlist.cpp.
Member Function Documentation
add()
template<class Generator > void OutputList::add () inline
Definition at line 46 of file outputlist.h.
References m_outputs.
Referenced by generateOutput().
addIndexItem()
void OutputList::addIndexItem (const char * s1, const char * s2) inline virtual
Implements BaseOutputDocInterface.
Definition at line 326 of file outputlist.h.
References BaseOutputDocInterface::addIndexItem(), and forall().
Referenced by MemberDefImpl::_writeEnumValues(), and ClassDefImpl::writeInlineDocumentation().
addWord()
void OutputList::addWord (const char * word, bool hiPriority) inline virtual
Implements CodeOutputInterface.
Definition at line 478 of file outputlist.h.
References CodeOutputInterface::addWord(), and forall().
clear()
void OutputList::clear () private
codify()
void OutputList::codify (const char * s) inline virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 135 of file outputlist.h.
References CodeOutputInterface::codify(), and forall().
debug()
void OutputList::debug () private
disable()
void OutputList::disable (OutputGenerator::OutputType o) virtual
Disables a specific output format (useful for OutputList only)
Implements OutputDocInterface.
Definition at line 88 of file outputlist.cpp.
References m_outputs.
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), DefinitionImpl::_writeSourceRefList(), endIndexHierarchy(), generateExampleDocs(), ClassDefImpl::showUsedFiles(), startIndexHierarchy(), FileDefImpl::startMemberDocumentation(), GroupDefImpl::startMemberDocumentation(), NamespaceDefImpl::startMemberDocumentation(), ClassDefImpl::startMemberDocumentation(), startTitle(), writeAnnotatedClassList(), writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), writeClassHierarchy(), ClassDefImpl::writeCollaborationGraph(), MemberDefImpl::writeDeclaration(), writeDefArgumentList(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), DirDefImpl::writeDirectoryGraph(), writeDirHierarchy(), MemberDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeExample(), writeExampleIndex(), writeFileIndex(), VhdlDocGen::writeFuncProcDocu(), GroupDefImpl::writeGroupGraph(), writeGroupHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), FileDefImpl::writeIncludeGraph(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), FileDefImpl::writeInlineClasses(), VhdlDocGen::writeInlineClassLink(), ClassDefImpl::writeInlineDocumentation(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), DefinitionImpl::writeSourceDef(), FileDefImpl::writeSourceHeader(), and VhdlDocGen::writeVHDLDeclaration().
disableAll()
void OutputList::disableAll () virtual
Disables all output formats (useful for OutputList only)
Implements OutputDocInterface.
Definition at line 80 of file outputlist.cpp.
References m_outputs.
Referenced by MemberDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), and PageDefImpl::writePageDocumentation().
disableAllBut()
void OutputList::disableAllBut (OutputGenerator::OutputType o) virtual
Disables all output formats except format o (useful for OutputList only)
Implements OutputDocInterface.
Definition at line 64 of file outputlist.cpp.
References m_outputs.
Referenced by MemberDefImpl::_writeEnumValues(), ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), endFile(), endFileWithNavPath(), generateDirDocs(), recursivelyAddGroupListToTitle(), ClassDefImpl::showUsedFiles(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), writeClassMemberIndexFiltered(), MemberDefImpl::writeDeclaration(), MemberList::writeDeclarations(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), MemberDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeFileIndex(), DirDefImpl::writeFileList(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeInheritedMemberDeclarations(), ClassDefImpl::writeInlineDocumentation(), ClassDefImpl::writeMemberList(), FileDefImpl::writeMemberPages(), GroupDefImpl::writeMemberPages(), NamespaceDefImpl::writeMemberPages(), ClassDefImpl::writeMemberPages(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), DefinitionImpl::writeNavigationPath(), PageDefImpl::writePageDocumentation(), writePageIndex(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), DefinitionImpl::writeSourceDef(), FileDefImpl::writeSourceLink(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), DefinitionImpl::writeToc(), writeUserGroupStubPage(), and VhdlDocGen::writeVHDLDeclaration().
docify()
void OutputList::docify (const char * s) inline virtual
Writes an ASCII string to the output. Converts characters that have A special meaning, like & in html.
Implements BaseOutputDocInterface.
Definition at line 133 of file outputlist.h.
References BaseOutputDocInterface::docify(), and forall().
Referenced by MemberDefImpl::_writeEnumValues(), MemberDefImpl::_writeGroupInclude(), DefinitionImpl::_writeSourceRefList(), generateExampleDocs(), ClassDefImpl::showUsedFiles(), startFonts(), writeAlphabeticalClassList(), writeAnnotatedClassList(), NamespaceDefImpl::writeBriefDescription(), writeClassLinkForMember(), writeClassTree(), writeClassTreeForList(), NamespaceSDict::writeDeclaration(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), writeDefArgumentList(), writeDirTreeNode(), MemberDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeExceptionListImpl(), writeFileLinkForMember(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), VhdlDocGen::writeFormatString(), VhdlDocGen::writeFuncProcDocu(), VhdlDocGen::writeFunctionProto(), writeGroupTreeNode(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), ClassDefImpl::writeInheritanceGraph(), writeInheritanceSpecifier(), MemberDefImpl::writeLink(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMemberList(), ClassDefImpl::writeMoreLink(), writeNamespaceLinkForMember(), GroupDefImpl::writePageDocumentation(), writePartialFilePath(), MemberList::writePlainDeclarations(), VhdlDocGen::writeProcedureProto(), VhdlDocGen::writeProcessProto(), writeSingleFileIndex(), DefinitionImpl::writeSourceDef(), VhdlDocGen::writeStringLink(), writeTemplatePrefix(), writeTemplateSpec(), writeUCFLink(), VhdlDocGen::writeVHDLDeclaration(), VhdlDocGen::writeVHDLDeclarations(), VhdlDocGen::writeVhdlLink(), and VhdlDocGen::writeVHDLTypeDocumentation().
enable()
void OutputList::enable (OutputGenerator::OutputType o) virtual
Enables a specific output format (useful for OutputList only)
Implements OutputDocInterface.
Definition at line 96 of file outputlist.cpp.
References m_outputs.
Referenced by FileDefImpl::endMemberDocumentation(), NamespaceDefImpl::endMemberDocumentation(), ClassDefImpl::endMemberDocumentation(), generateExampleDocs(), ClassDefImpl::showUsedFiles(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), writeDefArgumentList(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), MemberDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), VhdlDocGen::writeFuncProcDocu(), writeHierarchicalExceptionIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeIncludeFiles(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), FileDefImpl::writeInlineClasses(), VhdlDocGen::writeInlineClassLink(), PageDefImpl::writePageDocumentation(), DefinitionImpl::writeSourceDef(), and VhdlDocGen::writeVHDLDeclaration().
enableAll()
void OutputList::enableAll () virtual
Enables all output formats as far as they have been enabled in the config file. (useful for OutputList only)
Implements OutputDocInterface.
Definition at line 72 of file outputlist.cpp.
References m_outputs.
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), MemberDefImpl::_writeEnumValues(), writeDefArgumentList(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), DirDefImpl::writeDirectoryGraph(), DirDefImpl::writeDocumentation(), FileDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), VhdlDocGen::writeFuncProcDocu(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeFiles(), FileDefImpl::writeIncludeGraph(), ClassDefImpl::writeInheritanceGraph(), MemberList::writePlainDeclarations(), DefinitionImpl::writeSourceDef(), FileDefImpl::writeSourceFooter(), and FileDefImpl::writeSourceLink().
endAnonTypeScope()
void OutputList::endAnonTypeScope (int i1) inline
Definition at line 202 of file outputlist.h.
References OutputGenerator::endAnonTypeScope(), and forall().
Referenced by MemberDefImpl::writeDeclaration().
endBold()
void OutputList::endBold () inline virtual
End a section of text displayed in bold face.
Implements BaseOutputDocInterface.
Definition at line 295 of file outputlist.h.
References BaseOutputDocInterface::endBold(), and forall().
Referenced by VhdlDocGen::writeClassType(), ClassDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), MemberDefImpl::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), DirDefImpl::writeFileList(), VhdlDocGen::writeFormatString(), VhdlDocGen::writeFunctionProto(), MemberDefImpl::writeLink(), ClassDefImpl::writeMemberList(), writePartialFilePath(), VhdlDocGen::writeProcedureProto(), VhdlDocGen::writeProcessProto(), VhdlDocGen::writeRecordUnit(), writeSingleFileIndex(), VhdlDocGen::writeStringLink(), VhdlDocGen::writeVHDLDeclaration(), VhdlDocGen::writeVhdlLink(), and VhdlDocGen::writeVHDLTypeDocumentation().
endCallGraph()
void OutputList::endCallGraph (DotCallGraph & g) inline
Definition at line 388 of file outputlist.h.
References OutputGenerator::endCallGraph(), and forall().
Referenced by MemberDefImpl::_writeCallerGraph(), and MemberDefImpl::_writeCallGraph().
endCenter()
void OutputList::endCenter () inline virtual
Implements BaseOutputDocInterface.
Definition at line 285 of file outputlist.h.
References BaseOutputDocInterface::endCenter(), and forall().
endClassDiagram()
void OutputList::endClassDiagram (const ClassDiagram & d, const char * f, const char * n) inline
Definition at line 332 of file outputlist.h.
References OutputGenerator::endClassDiagram(), and forall().
Referenced by ClassDefImpl::writeInheritanceGraph().
endCodeFragment()
void OutputList::endCodeFragment (const char * style) inline virtual
Ends a block of code
Implements CodeOutputInterface.
Definition at line 234 of file outputlist.h.
References CodeOutputInterface::endCodeFragment(), and forall().
Referenced by MemberDefImpl::writeDocumentation(), DefinitionImpl::writeInlineCode(), VhdlDocGen::writeSource(), and FileDefImpl::writeSourceBody().
endCodeLine()
void OutputList::endCodeLine () inline virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 238 of file outputlist.h.
References CodeOutputInterface::endCodeLine(), and forall().
endConstraintDocs()
void OutputList::endConstraintDocs () inline
Definition at line 441 of file outputlist.h.
References OutputGenerator::endConstraintDocs(), and forall().
Referenced by writeTypeConstraints().
endConstraintList()
void OutputList::endConstraintList () inline
Definition at line 443 of file outputlist.h.
References OutputGenerator::endConstraintList(), and forall().
Referenced by writeTypeConstraints().
endConstraintParam()
void OutputList::endConstraintParam () inline
Definition at line 433 of file outputlist.h.
References OutputGenerator::endConstraintParam(), and forall().
Referenced by writeTypeConstraints().
endConstraintType()
void OutputList::endConstraintType () inline
Definition at line 437 of file outputlist.h.
References OutputGenerator::endConstraintType(), and forall().
Referenced by writeTypeConstraints().
endContents()
void OutputList::endContents () inline
Definition at line 354 of file outputlist.h.
References OutputGenerator::endContents(), and forall().
Referenced by endFile(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentationContents(), MemberList::writeDocumentationPage(), and FileDefImpl::writeSourceFooter().
endDescForItem()
void OutputList::endDescForItem () inline virtual
Implements BaseOutputDocInterface.
Definition at line 273 of file outputlist.h.
References BaseOutputDocInterface::endDescForItem(), and forall().
Referenced by MemberDefImpl::_writeExamples(), and ClassDefImpl::writeDetailedDocumentationBody().
endDescItem()
void OutputList::endDescItem () inline virtual
Ends an item of a description list and starts the description itself: e.g. </dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 269 of file outputlist.h.
References BaseOutputDocInterface::endDescItem(), and forall().
endDescription()
void OutputList::endDescription () inline virtual
Ends a description list: e.g. </dl> in HTML
Implements BaseOutputDocInterface.
Definition at line 265 of file outputlist.h.
References BaseOutputDocInterface::endDescription(), and forall().
endDescTable()
void OutputList::endDescTable () inline virtual
Implements BaseOutputDocInterface.
Definition at line 364 of file outputlist.h.
References BaseOutputDocInterface::endDescTable(), and forall().
Referenced by MemberDefImpl::_writeEnumValues().
endDescTableData()
void OutputList::endDescTableData () inline virtual
Implements BaseOutputDocInterface.
Definition at line 376 of file outputlist.h.
References BaseOutputDocInterface::endDescTableData(), and forall().
Referenced by MemberDefImpl::_writeEnumValues().
endDescTableRow()
void OutputList::endDescTableRow () inline virtual
Implements BaseOutputDocInterface.
Definition at line 368 of file outputlist.h.
References BaseOutputDocInterface::endDescTableRow(), and forall().
Referenced by MemberDefImpl::_writeEnumValues().
endDescTableTitle()
void OutputList::endDescTableTitle () inline virtual
Implements BaseOutputDocInterface.
Definition at line 372 of file outputlist.h.
References BaseOutputDocInterface::endDescTableTitle(), and forall().
Referenced by MemberDefImpl::_writeEnumValues().
endDirDepGraph()
void OutputList::endDirDepGraph (DotDirDeps & g) inline
Definition at line 392 of file outputlist.h.
References OutputGenerator::endDirDepGraph(), and forall().
Referenced by DirDefImpl::writeDirectoryGraph().
endDotGraph()
void OutputList::endDotGraph (DotClassGraph & g) inline
Definition at line 380 of file outputlist.h.
References OutputGenerator::endDotGraph(), and forall().
Referenced by ClassDefImpl::writeCollaborationGraph(), and ClassDefImpl::writeInheritanceGraph().
endDoxyAnchor()
void OutputList::endDoxyAnchor (const char * fn, const char * anchor) inline
Definition at line 259 of file outputlist.h.
References OutputGenerator::endDoxyAnchor(), and forall().
Referenced by MemberDefImpl::_writeEnumValues(), MemberDefImpl::writeDeclaration(), MemberDefImpl::writeDocumentation(), MemberDefImpl::writeMemberDocSimple(), MemberList::writePlainDeclarations(), and VhdlDocGen::writeVHDLDeclaration().
endEmphasis()
void OutputList::endEmphasis () inline virtual
Ends a section of text displayed in italic.
Implements BaseOutputDocInterface.
Definition at line 245 of file outputlist.h.
References BaseOutputDocInterface::endEmphasis(), and forall().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeVHDLDeclaration().
endExamples()
void OutputList::endExamples () inline virtual
Implements BaseOutputDocInterface.
Definition at line 312 of file outputlist.h.
References BaseOutputDocInterface::endExamples(), and forall().
Referenced by MemberDefImpl::_writeExamples(), and ClassDefImpl::writeDetailedDocumentationBody().
endFile()
void OutputList::endFile () inline
Definition at line 93 of file outputlist.h.
References OutputGenerator::endFile(), and forall().
Referenced by endFile().
endFontClass()
void OutputList::endFontClass () inline virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 472 of file outputlist.h.
References CodeOutputInterface::endFontClass(), and forall().
Referenced by startFonts().
endGroupCollaboration()
void OutputList::endGroupCollaboration (DotGroupCollaboration & g) inline
Definition at line 396 of file outputlist.h.
References OutputGenerator::endGroupCollaboration(), and forall().
Referenced by GroupDefImpl::writeGroupGraph().
endGroupHeader()
void OutputList::endGroupHeader (int extraLevels = 0) inline
Definition at line 166 of file outputlist.h.
References OutputGenerator::endGroupHeader(), and forall().
Referenced by FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), MemberList::writeDocumentation(), ClassSDict::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
endHeaderSection()
void OutputList::endHeaderSection () inline
Definition at line 178 of file outputlist.h.
References OutputGenerator::endHeaderSection(), and forall().
Referenced by endTitle(), GroupDefImpl::writeDocumentation(), and writeIndex().
endHtmlLink()
void OutputList::endHtmlLink () inline virtual
Ends a link started by startHtmlLink().
Implements BaseOutputDocInterface.
Definition at line 153 of file outputlist.h.
References BaseOutputDocInterface::endHtmlLink(), and forall().
endInclDepGraph()
void OutputList::endInclDepGraph (DotInclDepGraph & g) inline
Definition at line 384 of file outputlist.h.
References OutputGenerator::endInclDepGraph(), and forall().
Referenced by FileDefImpl::writeIncludedByGraph(), and FileDefImpl::writeIncludeGraph().
endIndent()
void OutputList::endIndent () inline
Definition at line 320 of file outputlist.h.
References OutputGenerator::endIndent(), and forall().
Referenced by MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
endIndexItem()
void OutputList::endIndexItem (const char * ref, const char * file) inline
Definition at line 131 of file outputlist.h.
References OutputGenerator::endIndexItem(), and forall().
Referenced by writeClassTree(), writeClassTreeForList(), writeDirTreeNode(), and writeGroupTreeNode().
endIndexKey()
void OutputList::endIndexKey () inline
Definition at line 119 of file outputlist.h.
References OutputGenerator::endIndexKey(), and forall().
Referenced by writeAnnotatedClassList(), writeNamespaceIndex(), and writeSingleFileIndex().
endIndexList()
void OutputList::endIndexList () inline
Definition at line 115 of file outputlist.h.
References OutputGenerator::endIndexList(), and forall().
Referenced by endIndexHierarchy(), writeAnnotatedClassList(), writeFileIndex(), and writeNamespaceIndex().
endIndexListItem()
void OutputList::endIndexListItem () inline
Definition at line 111 of file outputlist.h.
References OutputGenerator::endIndexListItem(), and forall().
Referenced by writeClassTree(), writeClassTreeForList(), writeDirTreeNode(), and writeGroupTreeNode().
endIndexSection()
void OutputList::endIndexSection (IndexSections is) inline
Definition at line 77 of file outputlist.h.
References OutputGenerator::endIndexSection(), and forall().
Referenced by writeIndex().
endIndexValue()
void OutputList::endIndexValue (const char * name, bool b) inline
Definition at line 123 of file outputlist.h.
References OutputGenerator::endIndexValue(), and forall().
Referenced by writeAnnotatedClassList(), writeNamespaceIndex(), and writeSingleFileIndex().
endInlineHeader()
void OutputList::endInlineHeader () inline
Definition at line 198 of file outputlist.h.
References OutputGenerator::endInlineHeader(), and forall().
Referenced by MemberList::writeDeclarations().
endInlineMemberDoc()
void OutputList::endInlineMemberDoc () inline
Definition at line 460 of file outputlist.h.
References OutputGenerator::endInlineMemberDoc(), and forall().
Referenced by MemberDefImpl::writeMemberDocSimple().
endInlineMemberName()
void OutputList::endInlineMemberName () inline
Definition at line 456 of file outputlist.h.
References OutputGenerator::endInlineMemberName(), and forall().
Referenced by MemberDefImpl::writeMemberDocSimple().
endInlineMemberType()
void OutputList::endInlineMemberType () inline
Definition at line 452 of file outputlist.h.
References OutputGenerator::endInlineMemberType(), and forall().
Referenced by MemberDefImpl::writeMemberDocSimple().
endItemList()
void OutputList::endItemList () inline virtual
Ends a bullet list: e.g. </ul> in html
Implements BaseOutputDocInterface.
Definition at line 127 of file outputlist.h.
References BaseOutputDocInterface::endItemList(), and forall().
Referenced by endIndexHierarchy(), ClassDefImpl::showUsedFiles(), and writeExampleIndex().
endItemListItem()
void OutputList::endItemListItem () inline virtual
Writes a list item for a bullet or enumerated list: e.g. </li> in html
Implements BaseOutputDocInterface.
Definition at line 170 of file outputlist.h.
References BaseOutputDocInterface::endItemListItem(), and forall().
Referenced by ClassDefImpl::showUsedFiles(), and writeExampleIndex().
endLabels()
void OutputList::endLabels () inline
Definition at line 467 of file outputlist.h.
References OutputGenerator::endLabels(), and forall().
Referenced by ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), and MemberDefImpl::writeDocumentation().
endMemberDeclaration()
void OutputList::endMemberDeclaration (const char * anchor, const char * inheritId) inline
Definition at line 303 of file outputlist.h.
References OutputGenerator::endMemberDeclaration(), and forall().
Referenced by NamespaceSDict::writeDeclaration(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), and DirDefImpl::writeSubDirList().
endMemberDescription()
void OutputList::endMemberDescription () inline
Definition at line 299 of file outputlist.h.
References OutputGenerator::endMemberDescription(), and forall().
Referenced by NamespaceSDict::writeDeclaration(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclaration().
endMemberDoc()
void OutputList::endMemberDoc (bool hasArgs) inline
Definition at line 253 of file outputlist.h.
References OutputGenerator::endMemberDoc(), and forall().
Referenced by MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
endMemberDocList()
void OutputList::endMemberDocList () inline
Definition at line 190 of file outputlist.h.
References OutputGenerator::endMemberDocList(), and forall().
Referenced by MemberList::writeDocumentation().
endMemberDocName()
void OutputList::endMemberDocName () inline
Definition at line 412 of file outputlist.h.
References OutputGenerator::endMemberDocName(), and forall().
Referenced by writeDefArgumentList(), MemberDefImpl::writeDocumentation(), VhdlDocGen::writeFuncProcDocu(), and ClassDefImpl::writeInlineDocumentation().
endMemberDocPrefixItem()
void OutputList::endMemberDocPrefixItem () inline
Definition at line 408 of file outputlist.h.
References OutputGenerator::endMemberDocPrefixItem(), and forall().
Referenced by MemberDefImpl::writeDocumentation().
endMemberDocSimple()
void OutputList::endMemberDocSimple (bool b) inline
Definition at line 448 of file outputlist.h.
References OutputGenerator::endMemberDocSimple(), and forall().
Referenced by MemberList::writeSimpleDocumentation().
endMemberGroup()
void OutputList::endMemberGroup (bool last) inline
Definition at line 222 of file outputlist.h.
References OutputGenerator::endMemberGroup(), and forall().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
endMemberGroupDocs()
void OutputList::endMemberGroupDocs () inline
Definition at line 218 of file outputlist.h.
References OutputGenerator::endMemberGroupDocs(), and forall().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
endMemberGroupHeader()
void OutputList::endMemberGroupHeader () inline
Definition at line 214 of file outputlist.h.
References OutputGenerator::endMemberGroupHeader(), and forall().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
endMemberHeader()
void OutputList::endMemberHeader () inline
Definition at line 182 of file outputlist.h.
References OutputGenerator::endMemberHeader(), and forall().
Referenced by ClassDefImpl::endMemberDeclarations(), NamespaceSDict::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), MemberList::writeDeclarations(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclarations().
endMemberItem()
void OutputList::endMemberItem () inline
Definition at line 206 of file outputlist.h.
References OutputGenerator::endMemberItem(), and forall().
Referenced by NamespaceSDict::writeDeclaration(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclaration().
endMemberList()
void OutputList::endMemberList () inline
Definition at line 194 of file outputlist.h.
References OutputGenerator::endMemberList(), and forall().
Referenced by NamespaceSDict::writeDeclaration(), ClassSDict::writeDeclaration(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), VhdlDocGen::writePlainVHDLDeclarations(), and DirDefImpl::writeSubDirList().
endMemberSections()
void OutputList::endMemberSections () inline
Definition at line 174 of file outputlist.h.
References OutputGenerator::endMemberSections(), and forall().
Referenced by DirDefImpl::endMemberDeclarations(), FileDefImpl::endMemberDeclarations(), GroupDefImpl::endMemberDeclarations(), NamespaceDefImpl::endMemberDeclarations(), and ClassDefImpl::endMemberDeclarations().
endMemberSubtitle()
void OutputList::endMemberSubtitle () inline
Definition at line 186 of file outputlist.h.
References OutputGenerator::endMemberSubtitle(), and forall().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
endMemberTemplateParams()
void OutputList::endMemberTemplateParams (const char * anchor, const char * inheritId) inline
Definition at line 210 of file outputlist.h.
References OutputGenerator::endMemberTemplateParams(), and forall().
Referenced by MemberDefImpl::writeDeclaration().
endPageDoc()
void OutputList::endPageDoc () inline
Definition at line 358 of file outputlist.h.
References OutputGenerator::endPageDoc(), and forall().
Referenced by PageDefImpl::writeDocumentation(), and writeIndex().
endPageRef()
void OutputList::endPageRef (const char * c, const char * a) inline virtual
Implements BaseOutputDocInterface.
Definition at line 336 of file outputlist.h.
References BaseOutputDocInterface::endPageRef(), and forall().
endParagraph()
void OutputList::endParagraph () inline virtual
Ends a paragraph
Implements BaseOutputDocInterface.
Definition at line 105 of file outputlist.h.
References BaseOutputDocInterface::endParagraph(), and forall().
Referenced by MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeGroupInclude(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), ClassDefImpl::showUsedFiles(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), FileDefImpl::writeDetailedDescription(), MemberDefImpl::writeDocumentation(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeMemberList(), DefinitionImpl::writeSourceDef(), and FileDefImpl::writeSourceLink().
endParameterList()
void OutputList::endParameterList () inline
Definition at line 424 of file outputlist.h.
References OutputGenerator::endParameterList(), and forall().
Referenced by MemberDefImpl::writeDocumentation().
endParameterName()
void OutputList::endParameterName (bool last, bool one, bool bracket) inline
Definition at line 420 of file outputlist.h.
References OutputGenerator::endParameterName(), and forall().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeRecUnitDocu().
endParameterType()
void OutputList::endParameterType () inline
Definition at line 416 of file outputlist.h.
References OutputGenerator::endParameterType(), and forall().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeRecUnitDocu().
endParamList()
void OutputList::endParamList () inline virtual
Implements BaseOutputDocInterface.
Definition at line 316 of file outputlist.h.
References BaseOutputDocInterface::endParamList(), and forall().
endPlainFile()
void OutputList::endPlainFile () inline
Definition at line 483 of file outputlist.h.
References OutputGenerator::endPlainFile(), and forall().
endProjectNumber()
void OutputList::endProjectNumber () inline
Definition at line 83 of file outputlist.h.
References OutputGenerator::endProjectNumber(), and forall().
Referenced by FileDefImpl::writeDocumentation(), and writeIndex().
endQuickIndices()
void OutputList::endQuickIndices () inline
Definition at line 340 of file outputlist.h.
References OutputGenerator::endQuickIndices(), and forall().
Referenced by startFile(), writeClassMemberIndexFiltered(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), writeFileMemberIndexFiltered(), writeIndex(), ClassDefImpl::writeMemberList(), writeNamespaceMemberIndexFiltered(), and FileDefImpl::writeSourceHeader().
endSection()
void OutputList::endSection (const char * lab, SectionType t) inline virtual
Implements BaseOutputDocInterface.
Definition at line 324 of file outputlist.h.
References BaseOutputDocInterface::endSection(), and forall().
Referenced by PageDefImpl::writeDocumentation(), GroupDefImpl::writePageDocumentation(), and PageDefImpl::writePageDocumentation().
endSmall()
void OutputList::endSmall () inline virtual
Implements BaseOutputDocInterface.
Definition at line 289 of file outputlist.h.
References BaseOutputDocInterface::endSmall(), and forall().
endSubsection()
void OutputList::endSubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 277 of file outputlist.h.
References BaseOutputDocInterface::endSubsection(), and forall().
endSubsubsection()
void OutputList::endSubsubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 281 of file outputlist.h.
References BaseOutputDocInterface::endSubsubsection(), and forall().
Referenced by writeTemplateSpec().
endTextBlock()
void OutputList::endTextBlock (bool paraBreak = FALSE) inline
Definition at line 402 of file outputlist.h.
References OutputGenerator::endTextBlock(), and forall().
Referenced by writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), writeClassMemberIndexFiltered(), FileDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeFiles(), FileDefImpl::writeIncludeGraph(), writeIndex(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), GroupDefImpl::writePageDocumentation(), PageDefImpl::writePageDocumentation(), and writePageIndex().
endTextLink()
void OutputList::endTextLink () inline virtual
Implements BaseOutputDocInterface.
Definition at line 149 of file outputlist.h.
References BaseOutputDocInterface::endTextLink(), and forall().
Referenced by DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), DirDefImpl::writeFileList(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMoreLink(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), FileDefImpl::writeSourceHeader(), FileDefImpl::writeSourceLink(), and VhdlDocGen::writeVHDLDeclaration().
endTitle()
void OutputList::endTitle () inline virtual
Implements BaseOutputDocInterface.
Definition at line 101 of file outputlist.h.
References BaseOutputDocInterface::endTitle(), and forall().
endTitleHead()
void OutputList::endTitleHead (const char * fileName, const char * name) inline
Definition at line 97 of file outputlist.h.
References OutputGenerator::endTitleHead(), and forall().
Referenced by endTitle(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), and writeIndex().
endTypewriter()
void OutputList::endTypewriter () inline virtual
End a section of text displayed in typewriter style.
Implements BaseOutputDocInterface.
Definition at line 162 of file outputlist.h.
References BaseOutputDocInterface::endTypewriter(), and forall().
Referenced by MemberDefImpl::_writeGroupInclude(), NamespaceDefImpl::writeBriefDescription(), writeClassTree(), writeClassTreeForList(), MemberDefImpl::writeDeclaration(), writeDefArgumentList(), writeDirTreeNode(), writeGroupTreeNode(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), and writeInheritanceSpecifier().
exceptionEntry()
void OutputList::exceptionEntry (const char * prefix, bool closeBracket) inline
Definition at line 426 of file outputlist.h.
References OutputGenerator::exceptionEntry(), and forall().
Referenced by writeExceptionListImpl().
forall()
template<typename T , class... Ts, class... As> void OutputList::forall (void(T::*)(Ts...) methodPtr, As &&... args) inline private
Definition at line 495 of file outputlist.h.
References m_outputs.
Referenced by addIndexItem(), addWord(), codify(), docify(), endAnonTypeScope(), endBold(), endCallGraph(), endCenter(), endClassDiagram(), endCodeFragment(), endCodeLine(), endConstraintDocs(), endConstraintList(), endConstraintParam(), endConstraintType(), endContents(), endDescForItem(), endDescItem(), endDescription(), endDescTable(), endDescTableData(), endDescTableRow(), endDescTableTitle(), endDirDepGraph(), endDotGraph(), endDoxyAnchor(), endEmphasis(), endExamples(), endFile(), endFontClass(), endGroupCollaboration(), endGroupHeader(), endHeaderSection(), endHtmlLink(), endInclDepGraph(), endIndent(), endIndexItem(), endIndexKey(), endIndexList(), endIndexListItem(), endIndexSection(), endIndexValue(), endInlineHeader(), endInlineMemberDoc(), endInlineMemberName(), endInlineMemberType(), endItemList(), endItemListItem(), endLabels(), endMemberDeclaration(), endMemberDescription(), endMemberDoc(), endMemberDocList(), endMemberDocName(), endMemberDocPrefixItem(), endMemberDocSimple(), endMemberGroup(), endMemberGroupDocs(), endMemberGroupHeader(), endMemberHeader(), endMemberItem(), endMemberList(), endMemberSections(), endMemberSubtitle(), endMemberTemplateParams(), endPageDoc(), endPageRef(), endParagraph(), endParameterList(), endParameterName(), endParameterType(), endParamList(), endPlainFile(), endProjectNumber(), endQuickIndices(), endSection(), endSmall(), endSubsection(), endSubsubsection(), endTextBlock(), endTextLink(), endTitle(), endTitleHead(), endTypewriter(), exceptionEntry(), insertMemberAlign(), insertMemberAlignLeft(), lastIndexPage(), lineBreak(), setCurrentDoc(), startAnonTypeScope(), startBold(), startCallGraph(), startCenter(), startClassDiagram(), startCodeFragment(), startCodeLine(), startConstraintDocs(), startConstraintList(), startConstraintParam(), startConstraintType(), startContents(), startDescForItem(), startDescItem(), startDescription(), startDescTable(), startDescTableData(), startDescTableRow(), startDescTableTitle(), startDirDepGraph(), startDotGraph(), startDoxyAnchor(), startEmphasis(), startExamples(), startFile(), startFontClass(), startGroupCollaboration(), startGroupHeader(), startHeaderSection(), startHtmlLink(), startInclDepGraph(), startIndent(), startIndexItem(), startIndexKey(), startIndexList(), startIndexListItem(), startIndexSection(), startIndexValue(), startInlineHeader(), startInlineMemberDoc(), startInlineMemberName(), startInlineMemberType(), startItemList(), startItemListItem(), startLabels(), startMemberDeclaration(), startMemberDescription(), startMemberDoc(), startMemberDocList(), startMemberDocName(), startMemberDocPrefixItem(), startMemberDocSimple(), startMemberGroup(), startMemberGroupDocs(), startMemberGroupHeader(), startMemberHeader(), startMemberItem(), startMemberList(), startMemberSections(), startMemberSubtitle(), startMemberTemplateParams(), startPageDoc(), startPageRef(), startParagraph(), startParameterList(), startParameterName(), startParameterType(), startParamList(), startPlainFile(), startProjectNumber(), startQuickIndices(), startSection(), startSmall(), startSubsection(), startSubsubsection(), startTextBlock(), startTextLink(), startTitle(), startTitleHead(), startTypewriter(), writeAnchor(), writeChar(), writeCodeAnchor(), writeCodeLink(), writeEndAnnoItem(), writeFooter(), writeGraphicalHierarchy(), writeInheritedSectionTitle(), writeLabel(), writeLatexSpacing(), writeLineNumber(), writeLogo(), writeNavigationPath(), writeNonBreakableSpace(), writeObjectLink(), writePageLink(), writeQuickLinks(), writeRuler(), writeSearchInfo(), writeSplitBar(), writeStartAnnoItem(), writeString(), writeStyleInfo(), writeSummaryLink(), writeSynopsis(), and writeTooltip().
generateDoc()
void OutputList::generateDoc (const char * fileName, int startLine, const Definition * ctx, const MemberDef * md, const QCString & docStr, bool indexWords, bool isExample, const char * exampleName, bool singleLine, bool linkFromIndex, bool markdownSupport)
Definition at line 130 of file outputlist.cpp.
References m_outputs, validatingParseDoc(), and writeDoc().
Referenced by MemberDefImpl::_writeEnumValues(), generateExampleDocs(), writeAnnotatedClassList(), ClassDefImpl::writeBriefDescription(), NamespaceSDict::writeDeclaration(), MemberList::writeDeclarations(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), GroupDefImpl::writeDirs(), MemberDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), writeGraphInfo(), writeIndex(), MemberDefImpl::writeMemberDocSimple(), writeNamespaceIndex(), GroupDefImpl::writeNestedGroups(), GroupDefImpl::writePageDocumentation(), PageDefImpl::writePageDocumentation(), writeSingleFileIndex(), DirDefImpl::writeSubDirList(), writeTypeConstraints(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVHDLDeclarations().
insertMemberAlign()
void OutputList::insertMemberAlign (bool templ = FALSE) inline
Definition at line 224 of file outputlist.h.
References forall(), and OutputGenerator::insertMemberAlign().
Referenced by NamespaceSDict::writeDeclaration(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), VhdlDocGen::writeFunctionProto(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), VhdlDocGen::writeRecordUnit(), DirDefImpl::writeSubDirList(), writeUCFLink(), and VhdlDocGen::writeVHDLDeclaration().
insertMemberAlignLeft()
void OutputList::insertMemberAlignLeft (int typ = 0, bool templ = FALSE) inline
Definition at line 226 of file outputlist.h.
References forall(), and OutputGenerator::insertMemberAlignLeft().
Referenced by VhdlDocGen::writeVHDLDeclaration().
isEnabled()
bool OutputList::isEnabled (OutputGenerator::OutputType o) virtual
Check whether a specific output format is currently enabled (useful for OutputList only)
Implements OutputDocInterface.
Definition at line 104 of file outputlist.cpp.
References m_outputs.
Referenced by MemberDefImpl::writeDeclaration(), writeDefArgumentList(), FileDefImpl::writeDetailedDescription(), FileDefImpl::writeInlineClasses(), and VhdlDocGen::writeVHDLDeclaration().
lastIndexPage()
void OutputList::lastIndexPage () inline
Definition at line 404 of file outputlist.h.
References forall(), and OutputGenerator::lastIndexPage().
Referenced by writeIndex().
lineBreak()
void OutputList::lineBreak (const char * style = 0) inline virtual
Implements BaseOutputDocInterface.
Definition at line 291 of file outputlist.h.
References forall(), and BaseOutputDocInterface::lineBreak().
Referenced by NamespaceDefImpl::writeBriefDescription(), MemberDefImpl::writeEnumDeclaration(), VhdlDocGen::writeFunctionProto(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), VhdlDocGen::writeProcedureProto(), writeTemplateSpec(), and VhdlDocGen::writeVhdlLink().
operator=()
OutputList & OutputList::operator= (const OutputList & ol)
Definition at line 47 of file outputlist.cpp.
References m_outputs.
parseText()
void OutputList::parseText (const QCString & textStr) virtual
Reimplemented from BaseOutputDocInterface.
Definition at line 168 of file outputlist.cpp.
References m_outputs, and validatingParseText().
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), ClassDefImpl::endMemberDeclarations(), ClassDefImpl::showUsedFiles(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), writeClassMemberIndexFiltered(), writeClassTree(), writeClassTreeForList(), ClassDefImpl::writeCollaborationGraph(), NamespaceSDict::writeDeclaration(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), MemberList::writeDeclarations(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), DirDefImpl::writeDirectoryGraph(), GroupDefImpl::writeDirs(), writeDirTreeNode(), MemberDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentation(), MemberList::writeDocumentation(), ClassSDict::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeExample(), writeExampleIndex(), writeFileIndex(), DirDefImpl::writeFileList(), writeFileMemberIndexFiltered(), GroupDefImpl::writeFiles(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), GroupDefImpl::writeGroupGraph(), writeGroupIndex(), writeGroupTreeNode(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeGraph(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeInlineDocumentation(), ClassDefImpl::writeMemberList(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), GroupDefImpl::writeNestedGroups(), PageDefImpl::writePageDocumentation(), writePageIndex(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), DefinitionImpl::writeSourceDef(), FileDefImpl::writeSourceHeader(), FileDefImpl::writeSourceLink(), DirDefImpl::writeSubDirList(), writeTypeConstraints(), writeUserGroupStubPage(), and VhdlDocGen::writeVHDLDeclarations().
popGeneratorState()
void OutputList::popGeneratorState () virtual
Pops the state of the current generator (or list of generators) on a stack. Should be preceded by a call the pushGeneratorState().
Implements OutputDocInterface.
Definition at line 122 of file outputlist.cpp.
References m_outputs.
Referenced by DefinitionImpl::_writeSourceRefList(), ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), endFile(), endFileWithNavPath(), endIndexHierarchy(), GroupDefImpl::endMemberDocumentation(), endTitle(), generateDirDocs(), recursivelyAddGroupListToTitle(), ClassDefImpl::showUsedFiles(), startIndexHierarchy(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedClassList(), writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), writeClassHierarchy(), writeClassMemberIndexFiltered(), ClassDefImpl::writeCollaborationGraph(), MemberDefImpl::writeDeclaration(), MemberList::writeDeclarations(), writeDefArgumentList(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), writeDirHierarchy(), MemberDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeExample(), writeExampleIndex(), writeFileIndex(), DirDefImpl::writeFileList(), writeFileMemberIndexFiltered(), writeGraphInfo(), GroupDefImpl::writeGroupGraph(), writeGroupHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeIncludeFiles(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeInheritedMemberDeclarations(), DefinitionImpl::writeInlineCode(), ClassDefImpl::writeInlineDocumentation(), ClassDefImpl::writeMemberList(), FileDefImpl::writeMemberPages(), GroupDefImpl::writeMemberPages(), NamespaceDefImpl::writeMemberPages(), ClassDefImpl::writeMemberPages(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), DefinitionImpl::writeNavigationPath(), PageDefImpl::writePageDocumentation(), writePageIndex(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), VhdlDocGen::writeSource(), DefinitionImpl::writeSourceDef(), FileDefImpl::writeSourceHeader(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), DefinitionImpl::writeToc(), writeUserGroupStubPage(), and VhdlDocGen::writeVHDLDeclaration().
pushGeneratorState()
void OutputList::pushGeneratorState () virtual
Appends the output generated by generator g to this generator.
Pushes the state of the current generator (or list of generators) on a stack.
Implements OutputDocInterface.
Definition at line 114 of file outputlist.cpp.
References m_outputs.
Referenced by DefinitionImpl::_writeSourceRefList(), ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), endFile(), endFileWithNavPath(), endIndexHierarchy(), generateDirDocs(), recursivelyAddGroupListToTitle(), ClassDefImpl::showUsedFiles(), startIndexHierarchy(), GroupDefImpl::startMemberDocumentation(), startTitle(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedClassList(), writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), writeClassHierarchy(), writeClassMemberIndexFiltered(), ClassDefImpl::writeCollaborationGraph(), MemberDefImpl::writeDeclaration(), MemberList::writeDeclarations(), writeDefArgumentList(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), writeDirHierarchy(), MemberDefImpl::writeDocumentation(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), writeExample(), writeExampleIndex(), writeFileIndex(), DirDefImpl::writeFileList(), writeFileMemberIndexFiltered(), writeGraphInfo(), GroupDefImpl::writeGroupGraph(), writeGroupHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeIncludeFiles(), writeIndex(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeInheritedMemberDeclarations(), DefinitionImpl::writeInlineCode(), ClassDefImpl::writeInlineDocumentation(), ClassDefImpl::writeMemberList(), FileDefImpl::writeMemberPages(), GroupDefImpl::writeMemberPages(), NamespaceDefImpl::writeMemberPages(), ClassDefImpl::writeMemberPages(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), DefinitionImpl::writeNavigationPath(), PageDefImpl::writePageDocumentation(), writePageIndex(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), VhdlDocGen::writeSource(), DefinitionImpl::writeSourceDef(), FileDefImpl::writeSourceHeader(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), DefinitionImpl::writeToc(), writeUserGroupStubPage(), and VhdlDocGen::writeVHDLDeclaration().
setCurrentDoc()
void OutputList::setCurrentDoc (const Definition * context, const char * anchor, bool isSourceFile) inline virtual
Implements CodeOutputInterface.
Definition at line 476 of file outputlist.h.
References forall(), and CodeOutputInterface::setCurrentDoc().
size()
size_t OutputList::size () const inline
Definition at line 51 of file outputlist.h.
References m_outputs.
Referenced by generateOutput().
startAnonTypeScope()
void OutputList::startAnonTypeScope (int i1) inline
Definition at line 200 of file outputlist.h.
References forall(), and OutputGenerator::startAnonTypeScope().
Referenced by MemberDefImpl::writeDeclaration().
startBold()
void OutputList::startBold () inline virtual
Changes the text font to bold face. The bold section ends with endBold()
Implements BaseOutputDocInterface.
Definition at line 293 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startBold().
Referenced by VhdlDocGen::writeClassType(), ClassDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), MemberDefImpl::writeDocumentation(), MemberDefImpl::writeEnumDeclaration(), DirDefImpl::writeFileList(), VhdlDocGen::writeFormatString(), VhdlDocGen::writeFunctionProto(), MemberDefImpl::writeLink(), ClassDefImpl::writeMemberList(), writePartialFilePath(), VhdlDocGen::writeProcedureProto(), VhdlDocGen::writeProcessProto(), VhdlDocGen::writeRecordUnit(), writeSingleFileIndex(), VhdlDocGen::writeStringLink(), VhdlDocGen::writeVHDLDeclaration(), VhdlDocGen::writeVhdlLink(), and VhdlDocGen::writeVHDLTypeDocumentation().
startCallGraph()
void OutputList::startCallGraph () inline
Definition at line 386 of file outputlist.h.
References forall(), and OutputGenerator::startCallGraph().
Referenced by MemberDefImpl::_writeCallerGraph(), and MemberDefImpl::_writeCallGraph().
startCenter()
void OutputList::startCenter () inline virtual
Implements BaseOutputDocInterface.
Definition at line 283 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startCenter().
startClassDiagram()
void OutputList::startClassDiagram () inline
Definition at line 330 of file outputlist.h.
References forall(), and OutputGenerator::startClassDiagram().
Referenced by ClassDefImpl::writeInheritanceGraph().
startCodeFragment()
void OutputList::startCodeFragment (const char * style) inline virtual
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 232 of file outputlist.h.
References forall(), and CodeOutputInterface::startCodeFragment().
Referenced by MemberDefImpl::writeDocumentation(), DefinitionImpl::writeInlineCode(), VhdlDocGen::writeSource(), and FileDefImpl::writeSourceBody().
startCodeLine()
void OutputList::startCodeLine (bool hasLineNumbers) inline virtual
Implements CodeOutputInterface.
Definition at line 236 of file outputlist.h.
References forall(), and CodeOutputInterface::startCodeLine().
startConstraintDocs()
void OutputList::startConstraintDocs () inline
Definition at line 439 of file outputlist.h.
References forall(), and OutputGenerator::startConstraintDocs().
Referenced by writeTypeConstraints().
startConstraintList()
void OutputList::startConstraintList (const char * header) inline
Definition at line 429 of file outputlist.h.
References forall(), and OutputGenerator::startConstraintList().
Referenced by writeTypeConstraints().
startConstraintParam()
void OutputList::startConstraintParam () inline
Definition at line 431 of file outputlist.h.
References forall(), and OutputGenerator::startConstraintParam().
Referenced by writeTypeConstraints().
startConstraintType()
void OutputList::startConstraintType () inline
Definition at line 435 of file outputlist.h.
References forall(), and OutputGenerator::startConstraintType().
Referenced by writeTypeConstraints().
startContents()
void OutputList::startContents () inline
Definition at line 352 of file outputlist.h.
References forall(), and OutputGenerator::startContents().
Referenced by generateExampleDocs(), writeAlphabeticalExceptionIndex(), writeAlphabeticalIndex(), writeAlphabeticalInterfaceIndex(), writeAlphabeticalStructIndex(), writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), writeClassMemberIndexFiltered(), DirDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), FileDefImpl::writeDocumentation(), GroupDefImpl::writeDocumentation(), NamespaceDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), ClassDefImpl::writeDocumentationContents(), MemberList::writeDocumentationPage(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGraphInfo(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), writeIndex(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), writePageIndex(), FileDefImpl::writeSourceHeader(), and writeUserGroupStubPage().
startDescForItem()
void OutputList::startDescForItem () inline virtual
Implements BaseOutputDocInterface.
Definition at line 271 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startDescForItem().
Referenced by MemberDefImpl::_writeExamples(), and ClassDefImpl::writeDetailedDocumentationBody().
startDescItem()
void OutputList::startDescItem () inline virtual
Starts an item of a description list: e.g. <dt> in HTML.
Implements BaseOutputDocInterface.
Definition at line 267 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startDescItem().
startDescription()
void OutputList::startDescription () inline virtual
Starts a description list: e.g. <dl> in HTML Items are surrounded by startDescItem() and endDescItem()
Implements BaseOutputDocInterface.
Definition at line 263 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startDescription().
startDescTable()
void OutputList::startDescTable (const char * title) inline virtual
Implements BaseOutputDocInterface.
Definition at line 362 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startDescTable().
Referenced by MemberDefImpl::_writeEnumValues().
startDescTableData()
void OutputList::startDescTableData () inline virtual
Implements BaseOutputDocInterface.
Definition at line 374 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startDescTableData().
Referenced by MemberDefImpl::_writeEnumValues().
startDescTableRow()
void OutputList::startDescTableRow () inline virtual
Implements BaseOutputDocInterface.
Definition at line 366 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startDescTableRow().
Referenced by MemberDefImpl::_writeEnumValues().
startDescTableTitle()
void OutputList::startDescTableTitle () inline virtual
Implements BaseOutputDocInterface.
Definition at line 370 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startDescTableTitle().
Referenced by MemberDefImpl::_writeEnumValues().
startDirDepGraph()
void OutputList::startDirDepGraph () inline
Definition at line 390 of file outputlist.h.
References forall(), and OutputGenerator::startDirDepGraph().
Referenced by DirDefImpl::writeDirectoryGraph().
startDotGraph()
void OutputList::startDotGraph () inline
Definition at line 378 of file outputlist.h.
References forall(), and OutputGenerator::startDotGraph().
Referenced by ClassDefImpl::writeCollaborationGraph(), and ClassDefImpl::writeInheritanceGraph().
startDoxyAnchor()
void OutputList::startDoxyAnchor (const char * fName, const char * manName, const char * anchor, const char * name, const char * args) inline
Definition at line 255 of file outputlist.h.
References forall(), and OutputGenerator::startDoxyAnchor().
Referenced by MemberDefImpl::_writeEnumValues(), MemberDefImpl::writeDeclaration(), MemberDefImpl::writeDocumentation(), MemberDefImpl::writeMemberDocSimple(), MemberList::writePlainDeclarations(), and VhdlDocGen::writeVHDLDeclaration().
startEmphasis()
void OutputList::startEmphasis () inline virtual
Changes the text font to italic. The italic section ends with endEmphasis()
Implements BaseOutputDocInterface.
Definition at line 243 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startEmphasis().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeVHDLDeclaration().
startExamples()
void OutputList::startExamples () inline virtual
Implements BaseOutputDocInterface.
Definition at line 310 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startExamples().
Referenced by MemberDefImpl::_writeExamples(), and ClassDefImpl::writeDetailedDocumentationBody().
startFile()
void OutputList::startFile (const char * name, const char * manName, const char * title) inline
Definition at line 87 of file outputlist.h.
References forall(), and OutputGenerator::startFile().
Referenced by startFile(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeIndex(), and writeNamespaceMemberIndexFiltered().
startFontClass()
void OutputList::startFontClass (const char * clsName) inline virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 470 of file outputlist.h.
References forall(), and CodeOutputInterface::startFontClass().
Referenced by startFonts().
startGroupCollaboration()
void OutputList::startGroupCollaboration () inline
Definition at line 394 of file outputlist.h.
References forall(), and OutputGenerator::startGroupCollaboration().
Referenced by GroupDefImpl::writeGroupGraph().
startGroupHeader()
void OutputList::startGroupHeader (int extraLevels = 0) inline
Definition at line 164 of file outputlist.h.
References forall(), and OutputGenerator::startGroupHeader().
Referenced by FileDefImpl::writeAuthorSection(), GroupDefImpl::writeAuthorSection(), NamespaceDefImpl::writeAuthorSection(), ClassDefImpl::writeAuthorSection(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), MemberList::writeDocumentation(), ClassSDict::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
startHeaderSection()
void OutputList::startHeaderSection () inline
Definition at line 176 of file outputlist.h.
References forall(), and OutputGenerator::startHeaderSection().
Referenced by startTitle(), GroupDefImpl::writeDocumentation(), and writeIndex().
startHtmlLink()
void OutputList::startHtmlLink (const char * url) inline virtual
Starts a (link to an) URL found in the documentation.
Parameters
url The URL to link to.
Implements BaseOutputDocInterface.
Definition at line 151 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startHtmlLink().
startInclDepGraph()
void OutputList::startInclDepGraph () inline
Definition at line 382 of file outputlist.h.
References forall(), and OutputGenerator::startInclDepGraph().
Referenced by FileDefImpl::writeIncludedByGraph(), and FileDefImpl::writeIncludeGraph().
startIndent()
void OutputList::startIndent () inline
Definition at line 318 of file outputlist.h.
References forall(), and OutputGenerator::startIndent().
Referenced by MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
startIndexItem()
void OutputList::startIndexItem (const char * ref, const char * file) inline
Definition at line 129 of file outputlist.h.
References forall(), and OutputGenerator::startIndexItem().
Referenced by writeClassTree(), writeClassTreeForList(), writeDirTreeNode(), and writeGroupTreeNode().
startIndexKey()
void OutputList::startIndexKey () inline
Definition at line 117 of file outputlist.h.
References forall(), and OutputGenerator::startIndexKey().
Referenced by writeAnnotatedClassList(), writeNamespaceIndex(), and writeSingleFileIndex().
startIndexList()
void OutputList::startIndexList () inline
Definition at line 113 of file outputlist.h.
References forall(), and OutputGenerator::startIndexList().
Referenced by startIndexHierarchy(), writeAnnotatedClassList(), writeFileIndex(), and writeNamespaceIndex().
startIndexListItem()
void OutputList::startIndexListItem () inline
Definition at line 109 of file outputlist.h.
References forall(), and OutputGenerator::startIndexListItem().
Referenced by writeClassTree(), writeClassTreeForList(), writeDirTreeNode(), and writeGroupTreeNode().
startIndexSection()
void OutputList::startIndexSection (IndexSections is) inline
Definition at line 75 of file outputlist.h.
References forall(), and OutputGenerator::startIndexSection().
Referenced by writeIndex().
startIndexValue()
void OutputList::startIndexValue (bool b) inline
Definition at line 121 of file outputlist.h.
References forall(), and OutputGenerator::startIndexValue().
Referenced by writeAnnotatedClassList(), writeNamespaceIndex(), and writeSingleFileIndex().
startInlineHeader()
void OutputList::startInlineHeader () inline
Definition at line 196 of file outputlist.h.
References forall(), and OutputGenerator::startInlineHeader().
Referenced by MemberList::writeDeclarations().
startInlineMemberDoc()
void OutputList::startInlineMemberDoc () inline
Definition at line 458 of file outputlist.h.
References forall(), and OutputGenerator::startInlineMemberDoc().
Referenced by MemberDefImpl::writeMemberDocSimple().
startInlineMemberName()
void OutputList::startInlineMemberName () inline
Definition at line 454 of file outputlist.h.
References forall(), and OutputGenerator::startInlineMemberName().
Referenced by MemberDefImpl::writeMemberDocSimple().
startInlineMemberType()
void OutputList::startInlineMemberType () inline
Definition at line 450 of file outputlist.h.
References forall(), and OutputGenerator::startInlineMemberType().
Referenced by MemberDefImpl::writeMemberDocSimple().
startItemList()
void OutputList::startItemList () inline virtual
Start of a bullet list: e.g. <ul> in html. startItemListItem() is Used for the bullet items.
Implements BaseOutputDocInterface.
Definition at line 125 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startItemList().
Referenced by ClassDefImpl::showUsedFiles(), startIndexHierarchy(), and writeExampleIndex().
startItemListItem()
void OutputList::startItemListItem () inline virtual
Writes a list item for a bullet or enumerated list: e.g. <li> in html
Implements BaseOutputDocInterface.
Definition at line 168 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startItemListItem().
Referenced by ClassDefImpl::showUsedFiles(), and writeExampleIndex().
startLabels()
void OutputList::startLabels () inline
Definition at line 463 of file outputlist.h.
References forall(), and OutputGenerator::startLabels().
Referenced by ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), and MemberDefImpl::writeDocumentation().
startMemberDeclaration()
void OutputList::startMemberDeclaration () inline
Definition at line 301 of file outputlist.h.
References forall(), and OutputGenerator::startMemberDeclaration().
Referenced by NamespaceSDict::writeDeclaration(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), and DirDefImpl::writeSubDirList().
startMemberDescription()
void OutputList::startMemberDescription (const char * anchor, const char * inheritId = 0, bool typ = false) inline
Definition at line 297 of file outputlist.h.
References forall(), and OutputGenerator::startMemberDescription().
Referenced by NamespaceSDict::writeDeclaration(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclaration().
startMemberDoc()
void OutputList::startMemberDoc (const char * clName, const char * memName, const char * anchor, const char * title, int memCount, int memTotal, bool showInline) inline
Definition at line 249 of file outputlist.h.
References forall(), and OutputGenerator::startMemberDoc().
Referenced by MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
startMemberDocList()
void OutputList::startMemberDocList () inline
Definition at line 188 of file outputlist.h.
References forall(), and OutputGenerator::startMemberDocList().
Referenced by MemberList::writeDocumentation().
startMemberDocName()
void OutputList::startMemberDocName (bool align) inline
Definition at line 410 of file outputlist.h.
References align(), forall(), and OutputGenerator::startMemberDocName().
Referenced by MemberDefImpl::writeDocumentation(), and ClassDefImpl::writeInlineDocumentation().
startMemberDocPrefixItem()
void OutputList::startMemberDocPrefixItem () inline
Definition at line 406 of file outputlist.h.
References forall(), and OutputGenerator::startMemberDocPrefixItem().
Referenced by MemberDefImpl::writeDocumentation().
startMemberDocSimple()
void OutputList::startMemberDocSimple (bool b) inline
Definition at line 446 of file outputlist.h.
References forall(), and OutputGenerator::startMemberDocSimple().
Referenced by MemberList::writeSimpleDocumentation().
startMemberGroup()
void OutputList::startMemberGroup () inline
Definition at line 220 of file outputlist.h.
References forall(), and OutputGenerator::startMemberGroup().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
startMemberGroupDocs()
void OutputList::startMemberGroupDocs () inline
Definition at line 216 of file outputlist.h.
References forall(), and OutputGenerator::startMemberGroupDocs().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
startMemberGroupHeader()
void OutputList::startMemberGroupHeader (bool b) inline
Definition at line 212 of file outputlist.h.
References forall(), and OutputGenerator::startMemberGroupHeader().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
startMemberHeader()
void OutputList::startMemberHeader (const char * anchor, int typ = 2) inline
Definition at line 180 of file outputlist.h.
References forall(), and OutputGenerator::startMemberHeader().
Referenced by ClassDefImpl::endMemberDeclarations(), NamespaceSDict::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), MemberList::writeDeclarations(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclarations().
startMemberItem()
void OutputList::startMemberItem (const char * anchor, int i1, const char * id = 0) inline
Definition at line 204 of file outputlist.h.
References forall(), and OutputGenerator::startMemberItem().
Referenced by NamespaceSDict::writeDeclaration(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), DirDefImpl::writeSubDirList(), and VhdlDocGen::writeVHDLDeclaration().
startMemberList()
void OutputList::startMemberList () inline
Definition at line 192 of file outputlist.h.
References forall(), and OutputGenerator::startMemberList().
Referenced by NamespaceSDict::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), GroupDefImpl::writeDirs(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), GroupDefImpl::writeNestedGroups(), MemberList::writePlainDeclarations(), VhdlDocGen::writePlainVHDLDeclarations(), and DirDefImpl::writeSubDirList().
startMemberSections()
void OutputList::startMemberSections () inline
Definition at line 172 of file outputlist.h.
References forall(), and OutputGenerator::startMemberSections().
Referenced by DirDefImpl::startMemberDeclarations(), FileDefImpl::startMemberDeclarations(), GroupDefImpl::startMemberDeclarations(), NamespaceDefImpl::startMemberDeclarations(), and ClassDefImpl::startMemberDeclarations().
startMemberSubtitle()
void OutputList::startMemberSubtitle () inline
Definition at line 184 of file outputlist.h.
References forall(), and OutputGenerator::startMemberSubtitle().
Referenced by MemberList::writeDeclarations(), and VhdlDocGen::writeVHDLDeclarations().
startMemberTemplateParams()
void OutputList::startMemberTemplateParams () inline
Definition at line 208 of file outputlist.h.
References forall(), and OutputGenerator::startMemberTemplateParams().
Referenced by MemberDefImpl::writeDeclaration().
startPageDoc()
void OutputList::startPageDoc (const char * pageTitle) inline
Definition at line 356 of file outputlist.h.
References forall(), and OutputGenerator::startPageDoc().
Referenced by PageDefImpl::writeDocumentation(), and writeIndex().
startPageRef()
void OutputList::startPageRef () inline virtual
Implements BaseOutputDocInterface.
Definition at line 334 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startPageRef().
startParagraph()
void OutputList::startParagraph (const char * classDef = 0) inline virtual
Starts a new paragraph
Starts a new paragraph
Implements BaseOutputDocInterface.
Definition at line 103 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startParagraph().
Referenced by MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeGroupInclude(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), ClassDefImpl::showUsedFiles(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), FileDefImpl::writeDetailedDescription(), MemberDefImpl::writeDocumentation(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), ClassDefImpl::writeInheritanceGraph(), ClassDefImpl::writeMemberList(), DefinitionImpl::writeSourceDef(), and FileDefImpl::writeSourceLink().
startParameterList()
void OutputList::startParameterList (bool openBracket) inline
Definition at line 422 of file outputlist.h.
References forall(), and OutputGenerator::startParameterList().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeRecUnitDocu().
startParameterName()
void OutputList::startParameterName (bool one) inline
Definition at line 418 of file outputlist.h.
References forall(), and OutputGenerator::startParameterName().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeRecUnitDocu().
startParameterType()
void OutputList::startParameterType (bool first, const char * key) inline
Definition at line 414 of file outputlist.h.
References forall(), and OutputGenerator::startParameterType().
Referenced by writeDefArgumentList(), VhdlDocGen::writeFuncProcDocu(), and VhdlDocGen::writeRecUnitDocu().
startParamList()
void OutputList::startParamList (ParamListTypes t, const char * title) inline virtual
Implements BaseOutputDocInterface.
Definition at line 314 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startParamList().
startPlainFile()
void OutputList::startPlainFile (const char * name) inline
Definition at line 481 of file outputlist.h.
References forall(), and OutputGenerator::startPlainFile().
startProjectNumber()
void OutputList::startProjectNumber () inline
Definition at line 81 of file outputlist.h.
References forall(), and OutputGenerator::startProjectNumber().
Referenced by FileDefImpl::writeDocumentation(), and writeIndex().
startQuickIndices()
void OutputList::startQuickIndices () inline
Definition at line 338 of file outputlist.h.
References forall(), and OutputGenerator::startQuickIndices().
Referenced by startFile(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeIndex(), and writeNamespaceMemberIndexFiltered().
startSection()
void OutputList::startSection (const char * lab, const char * title, SectionType t) inline virtual
Implements BaseOutputDocInterface.
Definition at line 322 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startSection().
Referenced by GroupDefImpl::writePageDocumentation(), and PageDefImpl::writePageDocumentation().
startSmall()
void OutputList::startSmall () inline virtual
Implements BaseOutputDocInterface.
Definition at line 287 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startSmall().
startSubsection()
void OutputList::startSubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 275 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startSubsection().
startSubsubsection()
void OutputList::startSubsubsection () inline virtual
Implements BaseOutputDocInterface.
Definition at line 279 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startSubsubsection().
Referenced by writeTemplateSpec().
startTextBlock()
void OutputList::startTextBlock (bool dense = FALSE) inline
Definition at line 400 of file outputlist.h.
References forall(), and OutputGenerator::startTextBlock().
Referenced by writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), writeClassMemberIndexFiltered(), FileDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), writeExampleIndex(), writeFileIndex(), writeFileMemberIndexFiltered(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeFiles(), FileDefImpl::writeIncludeGraph(), writeIndex(), writeNamespaceIndex(), writeNamespaceMemberIndexFiltered(), GroupDefImpl::writePageDocumentation(), PageDefImpl::writePageDocumentation(), and writePageIndex().
startTextLink()
void OutputList::startTextLink (const char * file, const char * anchor) inline virtual
Implements BaseOutputDocInterface.
Definition at line 147 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startTextLink().
Referenced by DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), DirDefImpl::writeFileList(), writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), writeGraphicalInterfaceHierarchy(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeMoreLink(), MemberList::writePlainDeclarations(), writeSingleFileIndex(), FileDefImpl::writeSourceHeader(), FileDefImpl::writeSourceLink(), and VhdlDocGen::writeVHDLDeclaration().
startTitle()
void OutputList::startTitle () inline virtual
Implements BaseOutputDocInterface.
Definition at line 99 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startTitle().
startTitleHead()
void OutputList::startTitleHead (const char * fileName) inline
Definition at line 95 of file outputlist.h.
References forall(), and OutputGenerator::startTitleHead().
Referenced by startTitle(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), and writeIndex().
startTypewriter()
void OutputList::startTypewriter () inline virtual
Changes the text font to fixed size. The section ends with endTypewriter()
Implements BaseOutputDocInterface.
Definition at line 160 of file outputlist.h.
References forall(), and BaseOutputDocInterface::startTypewriter().
Referenced by MemberDefImpl::_writeGroupInclude(), NamespaceDefImpl::writeBriefDescription(), writeClassTree(), writeClassTreeForList(), MemberDefImpl::writeDeclaration(), writeDefArgumentList(), writeDirTreeNode(), writeGroupTreeNode(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), and writeInheritanceSpecifier().
writeAnchor()
void OutputList::writeAnchor (const char * fileName, const char * name) inline virtual
Implements BaseOutputDocInterface.
Definition at line 230 of file outputlist.h.
References forall(), and BaseOutputDocInterface::writeAnchor().
Referenced by ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), writeIndex(), and ClassDefImpl::writeInlineDocumentation().
writeChar()
void OutputList::writeChar (char c) inline virtual
Writes a single ASCII character to the output. Converts characters that have a special meaning.
Implements BaseOutputDocInterface.
Definition at line 247 of file outputlist.h.
References forall(), and BaseOutputDocInterface::writeChar().
Referenced by MemberDefImpl::writeEnumDeclaration(), and VhdlDocGen::writeProcedureProto().
writeCodeAnchor()
void OutputList::writeCodeAnchor (const char * name) inline virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 474 of file outputlist.h.
References forall(), and CodeOutputInterface::writeCodeAnchor().
writeCodeLink()
void OutputList::writeCodeLink (const char * ref, const char * file, const char * anchor, const char * name, const char * tooltip) inline virtual
Writes a link to an object in a code fragment.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 140 of file outputlist.h.
References forall(), and CodeOutputInterface::writeCodeLink().
writeDoc()
void OutputList::writeDoc (DocRoot * root, const Definition * ctx, const MemberDef * md)
Definition at line 157 of file outputlist.cpp.
References m_outputs, and VhdlDocGen::setFlowMember().
Referenced by generateDoc(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), and MemberList::writePlainDeclarations().
writeEndAnnoItem()
void OutputList::writeEndAnnoItem (const char * name) inline
Definition at line 158 of file outputlist.h.
References forall(), and OutputGenerator::writeEndAnnoItem().
writeFooter()
void OutputList::writeFooter (const char * navPath) inline
Definition at line 91 of file outputlist.h.
References forall(), and OutputGenerator::writeFooter().
Referenced by endFile().
writeGraphicalHierarchy()
void OutputList::writeGraphicalHierarchy (DotGfxHierarchyTable & g) inline
Definition at line 398 of file outputlist.h.
References forall(), and OutputGenerator::writeGraphicalHierarchy().
Referenced by writeGraphicalClassHierarchy(), writeGraphicalExceptionHierarchy(), and writeGraphicalInterfaceHierarchy().
writeInheritedSectionTitle()
void OutputList::writeInheritedSectionTitle (const char * id, const char * ref, const char * file, const char * anchor, const char * title, const char * name) inline
Definition at line 305 of file outputlist.h.
References forall(), and OutputGenerator::writeInheritedSectionTitle().
Referenced by MemberList::writeDeclarations().
writeLabel()
void OutputList::writeLabel (const char * l, bool isLast) inline
Definition at line 465 of file outputlist.h.
References forall(), and OutputGenerator::writeLabel().
Referenced by ClassDefImpl::addClassAttributes(), NamespaceDefImpl::addNamespaceAttributes(), and MemberDefImpl::writeDocumentation().
writeLatexSpacing()
void OutputList::writeLatexSpacing () inline
Definition at line 261 of file outputlist.h.
References forall(), and OutputGenerator::writeLatexSpacing().
Referenced by MemberDefImpl::writeDeclaration().
writeLineNumber()
void OutputList::writeLineNumber (const char * ref, const char * file, const char * anchor, int lineNumber) inline virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
Implements CodeOutputInterface.
Definition at line 240 of file outputlist.h.
References forall(), and CodeOutputInterface::writeLineNumber().
writeLogo()
void OutputList::writeLogo () inline
Definition at line 346 of file outputlist.h.
References forall(), and OutputGenerator::writeLogo().
writeNavigationPath()
void OutputList::writeNavigationPath (const char * s) inline
Definition at line 344 of file outputlist.h.
References forall(), and OutputGenerator::writeNavigationPath().
Referenced by DefinitionImpl::writeNavigationPath().
writeNonBreakableSpace()
void OutputList::writeNonBreakableSpace (int num) inline virtual
Implements BaseOutputDocInterface.
Definition at line 360 of file outputlist.h.
References forall(), and BaseOutputDocInterface::writeNonBreakableSpace().
Referenced by writeAlphabeticalClassList(), MemberDefImpl::writeDeclaration(), and MemberDefImpl::writeDocumentation().
writeObjectLink()
void OutputList::writeObjectLink (const char * ref, const char * file, const char * anchor, const char * name) inline virtual
Writes a link to an object in the documentation.
Parameters
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
Implements BaseOutputDocInterface.
Definition at line 137 of file outputlist.h.
References forall(), and BaseOutputDocInterface::writeObjectLink().
Referenced by MemberDefImpl::_writeCategoryRelation(), MemberDefImpl::_writeGroupInclude(), MemberDefImpl::_writeReimplementedBy(), MemberDefImpl::_writeReimplements(), DefinitionImpl::_writeSourceRefList(), recursivelyAddGroupListToTitle(), ClassDefImpl::showUsedFiles(), writeAlphabeticalClassList(), writeAnnotatedClassList(), writeClassLinkForMember(), NamespaceSDict::writeDeclaration(), ClassDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDirs(), writeExample(), writeExampleIndex(), writeFileLinkForMember(), DirDefImpl::writeFileList(), GroupDefImpl::writeFiles(), FileDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFiles(), ClassDefImpl::writeIncludeFilesForSlice(), ClassDefImpl::writeInheritanceGraph(), writeLink(), MemberDefImpl::writeLink(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMemberList(), writeNamespaceIndex(), writeNamespaceLinkForMember(), GroupDefImpl::writeNestedGroups(), writePartialDirPath(), writePartialFilePath(), writeSingleFileIndex(), DefinitionImpl::writeSourceDef(), DirDefImpl::writeSubDirList(), VhdlDocGen::writeVHDLDeclaration(), and VhdlDocGen::writeVhdlLink().
writePageLink()
void OutputList::writePageLink (const char * name, bool first) inline
Definition at line 79 of file outputlist.h.
References forall(), and OutputGenerator::writePageLink().
Referenced by writeIndex().
writeQuickLinks()
void OutputList::writeQuickLinks (bool compact, HighlightedItem hli, const char * file) inline
Definition at line 348 of file outputlist.h.
References forall(), and OutputGenerator::writeQuickLinks().
Referenced by startFile(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeIndex(), and writeNamespaceMemberIndexFiltered().
writeRuler()
void OutputList::writeRuler () inline virtual
Writes a horizontal ruler to the output
Implements BaseOutputDocInterface.
Definition at line 228 of file outputlist.h.
References forall(), and BaseOutputDocInterface::writeRuler().
Referenced by ClassDefImpl::showUsedFiles(), ClassDefImpl::writeDetailedDescription(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), MemberList::writeDocumentation(), and ClassSDict::writeDocumentation().
writeSearchInfo()
void OutputList::writeSearchInfo () inline
Definition at line 89 of file outputlist.h.
References forall(), and OutputGenerator::writeSearchInfo().
Referenced by startFile(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeIndex(), and writeNamespaceMemberIndexFiltered().
writeSplitBar()
void OutputList::writeSplitBar (const char * name) inline
Definition at line 342 of file outputlist.h.
References forall(), and OutputGenerator::writeSplitBar().
Referenced by startFile(), writeClassMemberIndexFiltered(), writeFileMemberIndexFiltered(), writeIndex(), and writeNamespaceMemberIndexFiltered().
writeStartAnnoItem()
void OutputList::writeStartAnnoItem (const char * type, const char * file, const char * path, const char * name) inline
Definition at line 155 of file outputlist.h.
References forall(), and OutputGenerator::writeStartAnnoItem().
writeString()
void OutputList::writeString (const char * text) inline virtual
Writes an ASCII string to the output, without converting special characters.
Implements BaseOutputDocInterface.
Definition at line 107 of file outputlist.h.
References forall(), and BaseOutputDocInterface::writeString().
Referenced by MemberDefImpl::_writeEnumValues(), DefinitionImpl::_writeSourceRefList(), endFile(), endFileWithNavPath(), endQuickIndexItem(), endQuickIndexList(), recursivelyAddGroupListToTitle(), startQuickIndexItem(), startQuickIndexList(), writeAlphabeticalClassList(), writeAnnotatedClassList(), writeAnnotatedExceptionIndex(), writeAnnotatedIndex(), writeAnnotatedInterfaceIndex(), writeAnnotatedStructIndex(), ClassDefImpl::writeAuthorSection(), DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), ClassDefImpl::writeBriefDescription(), writeClassLinkForMember(), writeClassMemberIndexFiltered(), VhdlDocGen::writeClassType(), MemberDefImpl::writeDeclaration(), ClassDefImpl::writeDeclarationLink(), DirDefImpl::writeDetailedDescription(), FileDefImpl::writeDetailedDescription(), GroupDefImpl::writeDetailedDescription(), NamespaceDefImpl::writeDetailedDescription(), ClassDefImpl::writeDetailedDocumentationBody(), MemberDefImpl::writeDocumentation(), DirRelation::writeDocumentation(), GroupDefImpl::writeDocumentation(), PageDefImpl::writeDocumentation(), MemberList::writeDocumentationPage(), MemberDefImpl::writeEnumDeclaration(), writeExample(), writeExampleIndex(), writeFileIndex(), writeFileLinkForMember(), writeFileMemberIndexFiltered(), writeGroupIndex(), writeHierarchicalExceptionIndex(), writeHierarchicalIndex(), writeHierarchicalInterfaceIndex(), ClassDefImpl::writeInlineDocumentation(), MemberDefImpl::writeMemberDocSimple(), ClassDefImpl::writeMemberList(), ClassDefImpl::writeMoreLink(), writeNamespaceIndex(), writeNamespaceLinkForMember(), writeNamespaceMemberIndexFiltered(), PageDefImpl::writePageDocumentation(), writePageIndex(), writePartialDirPath(), writePartialFilePath(), MemberList::writePlainDeclarations(), writeQuickMemberIndex(), FileDefImpl::writeQuickMemberLinks(), GroupDefImpl::writeQuickMemberLinks(), NamespaceDefImpl::writeQuickMemberLinks(), ClassDefImpl::writeQuickMemberLinks(), ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), NamespaceDefImpl::writeSummaryLinks(), writeTemplateSpec(), DefinitionImpl::writeToc(), writeUCFLink(), and writeUserGroupStubPage().
writeStyleInfo()
void OutputList::writeStyleInfo (int part) inline
Definition at line 85 of file outputlist.h.
References forall(), and OutputGenerator::writeStyleInfo().
Referenced by generateOutput().
writeSummaryLink()
void OutputList::writeSummaryLink (const char * file, const char * anchor, const char * title, bool first) inline
Definition at line 350 of file outputlist.h.
References forall(), and OutputGenerator::writeSummaryLink().
Referenced by ClassDefImpl::writeSummaryLinks(), FileDefImpl::writeSummaryLinks(), GroupDefImpl::writeSummaryLinks(), and NamespaceDefImpl::writeSummaryLinks().
writeSynopsis()
void OutputList::writeSynopsis () inline
Definition at line 328 of file outputlist.h.
References forall(), and OutputGenerator::writeSynopsis().
Referenced by DirDefImpl::writeBriefDescription(), FileDefImpl::writeBriefDescription(), GroupDefImpl::writeBriefDescription(), NamespaceDefImpl::writeBriefDescription(), and ClassDefImpl::writeBriefDescription().
writeTooltip()
void OutputList::writeTooltip (const char * id, const DocLinkInfo & docInfo, const char * decl, const char * desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) inline virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 144 of file outputlist.h.
References forall(), and CodeOutputInterface::writeTooltip().
Member Data Documentation
m_outputs
std::vector< std::unique_ptr<OutputGenerator> > OutputList::m_outputs private
Definition at line 503 of file outputlist.h.
Referenced by add(), disable(), disableAll(), disableAllBut(), enable(), enableAll(), forall(), generateDoc(), isEnabled(), operator=(), OutputList(), parseText(), popGeneratorState(), pushGeneratorState(), size(), and writeDoc().
The documentation for this class was generated from the following files:
src/outputlist.h
src/outputlist.cpp