Doxygen: src/ftextstream.h File Reference
ftextstream.h File Reference
#include <stdio.h>
#include <qiodevice.h>
#include <qstring.h>
#include <qgstring.h>
Classes
class FTextStream
Simplified and optimized version of QTextStream.
Typedefs
typedef FTextStream &(* FTSFUNC) (FTextStream &)
Functions
FTextStream & operator<< (FTextStream &s, FTSFUNC f)
FTextStream & endl (FTextStream &s)
Typedef Documentation
FTSFUNC
typedef FTextStream&(* FTSFUNC) (FTextStream &)
Definition at line 67 of file ftextstream.h.
Function Documentation
endl()
FTextStream& endl (FTextStream & s) inline
Definition at line 72 of file ftextstream.h.
Referenced by DocSets::addContentsItem(), RTFGenerator::addIndexItem(), addIndexTerm(), RTFGenerator::beginRTFDocument(), EclipseHelp::closedTag(), DotGraph::computeGraph(), DotGfxHierarchyTable::computeTheGraph(), convertMapFile(), HtmlHelp::Private::createProjectFile(), DocSets::decContentsDepth(), EclipseHelp::decContentsDepth(), TreeDiagram::drawConnectors(), dumpSymbol(), LatexGenerator::endAnonTypeScope(), RTFGenerator::endCallGraph(), HtmlGenerator::endCenter(), LatexGenerator::endCenter(), DocbookGenerator::endClassDiagram(), HtmlGenerator::endClassDiagram(), RTFGenerator::endClassDiagram(), ManGenerator::endCodeFragment(), XMLCodeGenerator::endCodeFragment(), RTFGenerator::endCodeFragment(), DocbookCodeGenerator::endCodeLine(), XMLCodeGenerator::endCodeLine(), HtmlGenerator::endConstraintDocs(), ManGenerator::endConstraintDocs(), RTFGenerator::endConstraintDocs(), DocbookGenerator::endConstraintList(), HtmlGenerator::endConstraintList(), LatexGenerator::endConstraintList(), RTFGenerator::endConstraintList(), RTFGenerator::endConstraintParam(), DocbookGenerator::endConstraintType(), RTFGenerator::endConstraintType(), HtmlGenerator::endContents(), RTFGenerator::endDescForItem(), LatexGenerator::endDescItem(), ManGenerator::endDescItem(), RTFGenerator::endDescItem(), LatexGenerator::endDescList(), HtmlGenerator::endDescription(), LatexGenerator::endDescription(), RTFGenerator::endDescription(), DocbookGenerator::endDescTable(), HtmlGenerator::endDescTable(), LatexGenerator::endDescTable(), RTFGenerator::endDescTable(), LatexGenerator::endDescTableData(), RTFGenerator::endDescTableData(), HtmlGenerator::endDescTableRow(), RTFGenerator::endDescTableTitle(), DocbookDocVisitor::endDiaFile(), RTFGenerator::endDirDepGraph(), DocbookDocVisitor::endDotFile(), RTFGenerator::endDotGraph(), RTFGenerator::endDoxyAnchor(), DocbookGenerator::endExamples(), HtmlGenerator::endExamples(), LatexGenerator::endExamples(), RTFGenerator::endExamples(), DocbookGenerator::endFile(), ManGenerator::endFile(), DocbookGenerator::endGroupHeader(), HtmlGenerator::endGroupHeader(), LatexGenerator::endGroupHeader(), ManGenerator::endGroupHeader(), RTFGenerator::endGroupHeader(), HtmlGenerator::endHeaderSection(), RTFGenerator::endHtmlLink(), RTFGenerator::endInclDepGraph(), HtmlGenerator::endIndent(), RTFGenerator::endIndent(), LatexGenerator::endIndexItem(), RTFGenerator::endIndexItem(), RTFGenerator::endIndexKey(), HtmlGenerator::endIndexList(), LatexGenerator::endIndexList(), RTFGenerator::endIndexList(), HtmlGenerator::endIndexListItem(), RTFGenerator::endIndexListItem(), DocbookGenerator::endIndexSection(), RTFGenerator::endIndexSection(), HtmlGenerator::endIndexValue(), LatexGenerator::endIndexValue(), RTFGenerator::endIndexValue(), HtmlGenerator::endInlineHeader(), LatexGenerator::endInlineHeader(), ManGenerator::endInlineHeader(), RTFGenerator::endInlineHeader(), HtmlGenerator::endInlineMemberDoc(), LatexGenerator::endInlineMemberDoc(), ManGenerator::endInlineMemberDoc(), RTFGenerator::endInlineMemberDoc(), HtmlGenerator::endInlineMemberName(), LatexGenerator::endInlineMemberName(), RTFGenerator::endInlineMemberName(), HtmlGenerator::endInlineMemberType(), LatexGenerator::endInlineMemberType(), RTFGenerator::endInlineMemberType(), HtmlGenerator::endItemList(), LatexGenerator::endItemList(), RTFGenerator::endItemList(), RTFGenerator::endItemListItem(), HtmlGenerator::endLabels(), HtmlGenerator::endMemberDescription(), RTFGenerator::endMemberDescription(), HtmlGenerator::endMemberDoc(), RTFGenerator::endMemberDoc(), HtmlGenerator::endMemberDocList(), HtmlGenerator::endMemberDocName(), HtmlGenerator::endMemberDocPrefixItem(), LatexGenerator::endMemberDocPrefixItem(), HtmlGenerator::endMemberDocSimple(), LatexGenerator::endMemberDocSimple(), ManGenerator::endMemberDocSimple(), RTFGenerator::endMemberDocSimple(), DocbookGenerator::endMemberGroup(), LatexGenerator::endMemberGroup(), RTFGenerator::endMemberGroup(), HtmlGenerator::endMemberGroupDocs(), RTFGenerator::endMemberGroupDocs(), DocbookGenerator::endMemberGroupHeader(), HtmlGenerator::endMemberGroupHeader(), LatexGenerator::endMemberGroupHeader(), RTFGenerator::endMemberGroupHeader(), DocbookGenerator::endMemberHeader(), HtmlGenerator::endMemberHeader(), LatexGenerator::endMemberHeader(), DocbookGenerator::endMemberItem(), HtmlGenerator::endMemberItem(), LatexGenerator::endMemberItem(), RTFGenerator::endMemberItem(), DocbookGenerator::endMemberList(), HtmlGenerator::endMemberList(), LatexGenerator::endMemberList(), RTFGenerator::endMemberList(), HtmlGenerator::endMemberSections(), HtmlGenerator::endMemberSubtitle(), RTFGenerator::endMemberSubtitle(), HtmlGenerator::endMemberTemplateParams(), DocbookDocVisitor::endMscFile(), HtmlGenerator::endPageDoc(), DocbookGenerator::endParagraph(), HtmlGenerator::endParagraph(), LatexGenerator::endParagraph(), RTFGenerator::endParagraph(), HtmlGenerator::endParameterList(), HtmlGenerator::endParameterName(), HtmlGenerator::endParameterType(), RTFGenerator::endParameterType(), LatexGenerator::endParamList(), RTFGenerator::endParamList(), RTFGenerator::endProjectNumber(), HtmlGenerator::endQuickIndices(), LatexGenerator::endSection(), RTFGenerator::endSection(), endSectionContent(), endSectionHeader(), endSectionSummary(), HtmlGenerator::endSmall(), HtmlGenerator::endSubsection(), LatexGenerator::endSubsection(), RTFGenerator::endSubsection(), DocbookGenerator::endSubsubsection(), HtmlGenerator::endSubsubsection(), LatexGenerator::endSubsubsection(), RTFGenerator::endSubsubsection(), RTFGenerator::endTextBlock(), RTFGenerator::endTextLink(), HtmlGenerator::endTitleHead(), ManGenerator::endTitleHead(), LatexGenerator::endTitleHead(), RTFGenerator::endTitleHead(), DocbookGenerator::endTitleHead(), DocbookGenerator::endTypewriter(), HtmlGenerator::exceptionEntry(), RTFGenerator::exceptionEntry(), RTFDocVisitor::filter(), DocSets::finalize(), EclipseHelp::finalize(), DotGraph::generateCode(), generateDEF(), generateDEFClassSection(), generateDEFForClass(), generateDEFForFile(), generateDEFForMember(), generateDEFForNamespace(), generateDEFSection(), FormulaManager::generateImages(), generateJSNavTree(), generateJSTree(), CitationManager::generatePage(), PerlModGenerator::generatePerlModForClass(), FTVHelp::generateTree(), generateXML(), generateXMLForClass(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForMember(), generateXMLForNamespace(), generateXMLForPage(), generateXMLSection(), DocSets::incContentsDepth(), RTFDocVisitor::includePicturePostRTF(), RTFDocVisitor::includePicturePreRTF(), ClassContext::Private::inheritanceDiagram(), HtmlGenerator::init(), DocSets::initialize(), EclipseHelp::initialize(), insertMapFile(), HtmlGenerator::insertMemberAlign(), vhdl::parser::TokenManager::lexicalError(), DocbookGenerator::lineBreak(), ManGenerator::lineBreak(), HtmlGenerator::lineBreak(), RTFGenerator::lineBreak(), LatexGenerator::newParagraph(), ManGenerator::newParagraph(), RTFGenerator::newParagraph(), EclipseHelp::openedTag(), preProcessFile(), TemplateNodeMsg::render(), renderMemberIndicesAsJs(), renderQuickLinksAsJs(), RTFGenerator::rtfwriteRuler_doubleline(), RTFGenerator::rtfwriteRuler_emboss(), RTFGenerator::rtfwriteRuler_thick(), RTFGenerator::rtfwriteRuler_thin(), DotFilePatcher::run(), LatexGenerator::startAnonTypeScope(), RTFGenerator::startCallGraph(), HtmlGenerator::startCenter(), LatexGenerator::startCenter(), RTFGenerator::startCenter(), RTFGenerator::startClassDiagram(), ManGenerator::startCodeFragment(), XMLCodeGenerator::startCodeFragment(), RTFGenerator::startCodeFragment(), RTFGenerator::startConstraintDocs(), DocbookGenerator::startConstraintList(), HtmlGenerator::startConstraintList(), LatexGenerator::startConstraintList(), ManGenerator::startConstraintList(), RTFGenerator::startConstraintList(), RTFGenerator::startConstraintParam(), RTFGenerator::startConstraintType(), HtmlGenerator::startContents(), LatexGenerator::startDescForItem(), ManGenerator::startDescForItem(), RTFGenerator::startDescForItem(), ManGenerator::startDescItem(), RTFGenerator::startDescItem(), ManGenerator::startDescList(), RTFGenerator::startDescList(), HtmlGenerator::startDescription(), LatexGenerator::startDescription(), RTFGenerator::startDescription(), DocbookGenerator::startDescTable(), ManGenerator::startDescTable(), HtmlGenerator::startDescTable(), LatexGenerator::startDescTable(), RTFGenerator::startDescTable(), ManGenerator::startDescTableData(), RTFGenerator::startDescTableData(), RTFGenerator::startDescTableTitle(), DocbookDocVisitor::startDiaFile(), RTFGenerator::startDirDepGraph(), DocbookDocVisitor::startDotFile(), RTFGenerator::startDotGraph(), LatexGenerator::startDoxyAnchor(), ManGenerator::startDoxyAnchor(), RTFGenerator::startDoxyAnchor(), ManGenerator::startExamples(), RTFGenerator::startExamples(), DocbookGenerator::startFile(), HtmlGenerator::startFile(), DocbookGenerator::startGroupHeader(), ManGenerator::startGroupHeader(), RTFGenerator::startGroupHeader(), HtmlGenerator::startHeaderSection(), RTFGenerator::startInclDepGraph(), HtmlGenerator::startIndent(), RTFGenerator::startIndent(), RTFGenerator::startIndexItem(), RTFGenerator::startIndexKey(), HtmlGenerator::startIndexList(), LatexGenerator::startIndexList(), RTFGenerator::startIndexList(), RTFGenerator::startIndexListItem(), DocbookGenerator::startIndexSection(), RTFGenerator::startIndexValue(), HtmlGenerator::startInlineHeader(), ManGenerator::startInlineHeader(), RTFGenerator::startInlineHeader(), HtmlGenerator::startInlineMemberDoc(), RTFGenerator::startInlineMemberDoc(), HtmlGenerator::startInlineMemberName(), RTFGenerator::startInlineMemberName(), HtmlGenerator::startInlineMemberType(), RTFGenerator::startInlineMemberType(), HtmlGenerator::startItemList(), LatexGenerator::startItemList(), RTFGenerator::startItemList(), LatexGenerator::startItemListItem(), ManGenerator::startItemListItem(), RTFGenerator::startItemListItem(), HtmlGenerator::startLabels(), RTFGenerator::startMemberDescription(), HtmlGenerator::startMemberDescription(), DocbookGenerator::startMemberDoc(), LatexGenerator::startMemberDoc(), ManGenerator::startMemberDoc(), RTFGenerator::startMemberDoc(), HtmlGenerator::startMemberDoc(), HtmlGenerator::startMemberDocList(), HtmlGenerator::startMemberDocName(), HtmlGenerator::startMemberDocPrefixItem(), HtmlGenerator::startMemberDocSimple(), LatexGenerator::startMemberDocSimple(), ManGenerator::startMemberDocSimple(), RTFGenerator::startMemberDocSimple(), RTFGenerator::startMemberGroup(), RTFGenerator::startMemberGroupDocs(), RTFGenerator::startMemberGroupHeader(), HtmlGenerator::startMemberHeader(), ManGenerator::startMemberHeader(), DocbookGenerator::startMemberHeader(), DocbookGenerator::startMemberItem(), LatexGenerator::startMemberItem(), RTFGenerator::startMemberItem(), HtmlGenerator::startMemberItem(), DocbookGenerator::startMemberList(), HtmlGenerator::startMemberList(), LatexGenerator::startMemberList(), RTFGenerator::startMemberList(), HtmlGenerator::startMemberSections(), HtmlGenerator::startMemberSubtitle(), RTFGenerator::startMemberSubtitle(), DocbookDocVisitor::startMscFile(), DocbookGenerator::startParagraph(), HtmlGenerator::startParagraph(), LatexGenerator::startParagraph(), ManGenerator::startParagraph(), RTFGenerator::startParagraph(), HtmlGenerator::startParameterList(), HtmlGenerator::startParameterName(), HtmlGenerator::startParameterType(), RTFGenerator::startParameterType(), RTFGenerator::startParamList(), ManGenerator::startParamList(), RTFGenerator::startProjectNumber(), RTFGenerator::startSection(), startSectionContent(), startSectionHeader(), startSectionSummary(), HtmlGenerator::startSmall(), ManGenerator::startSubsection(), ManGenerator::startSubsubsection(), RTFGenerator::startSubsubsection(), RTFGenerator::startTextBlock(), ManGenerator::startTitle(), RTFGenerator::startTitle(), HtmlGenerator::startTitleHead(), RTFGenerator::startTitleHead(), LatexDocVisitor::visit(), XmlDocVisitor::visit(), DocbookDocVisitor::visit(), ManDocVisitor::visit(), RTFDocVisitor::visit(), HtmlDocVisitor::visit(), ManDocVisitor::visitPost(), RTFDocVisitor::visitPost(), HtmlDocVisitor::visitPost(), DocbookDocVisitor::visitPost(), LatexDocVisitor::visitPost(), XmlDocVisitor::visitPost(), visitPostCaption(), DocbookDocVisitor::visitPostEnd(), visitPostEnd(), RTFDocVisitor::visitPre(), ManDocVisitor::visitPre(), DocbookDocVisitor::visitPre(), HtmlDocVisitor::visitPre(), XmlDocVisitor::visitPre(), LatexDocVisitor::visitPre(), visitPreCaption(), DocbookDocVisitor::visitPreStart(), SearchIndexExternal::write(), DotGroupCollaboration::Edge::write(), LatexGenerator::writeAnchor(), RTFGenerator::writeAnchor(), DotNode::writeArrow(), DotNode::writeBox(), NamespaceDefImpl::writeClassesToTagFile(), FileDefImpl::writeClassesToTagFile(), RTFGenerator::writeCodeLink(), DotNode::writeDEF(), writeDefaultHeaderPart1(), writeDefaultQuickLinks(), HtmlDocVisitor::writeDiaFile(), DefinitionImpl::writeDocAnchorsToTagFile(), DotNode::writeDocbook(), writeDotImageMapFromFile(), EmojiEntityMapper::writeEmojiFile(), HtmlGenerator::writeEndAnnoItem(), ManGenerator::writeEndAnnoItem(), LatexGenerator::writeEndAnnoItem(), RTFGenerator::writeEndAnnoItem(), HtmlGenerator::writeExternalSearchPage(), HtmlHelpIndex::writeFields(), ClassDiagram::writeFigure(), HtmlGenerator::writeFooterFile(), LatexGenerator::writeFooterFile(), DotGfxHierarchyTable::writeGraph(), DotGraph::writeGraphFooter(), DotGroupCollaboration::writeGraphHeader(), DotGraph::writeGraphHeader(), LatexGenerator::writeHeaderFile(), HtmlGenerator::writeHeaderFile(), HtmlGenerator::writeInheritedSectionTitle(), writeInnerClasses(), writeInnerDirs(), writeInnerFiles(), writeInnerGroups(), writeInnerNamespaces(), writeInnerPages(), writeJavaScriptSearchIndex(), HtmlGenerator::writeLabel(), writeLatexMakefile(), RTFGenerator::writeLineNumber(), writeListOfAllMembers(), writeMakeBat(), writeMapArea(), writeMemberReference(), writeMenuData(), writeMscImageMapFromFile(), RTFGenerator::writeObjectLink(), DocbookGenerator::writePageLink(), RTFGenerator::writePageLink(), HtmlDocVisitor::writePlantUMLFile(), DocbookGenerator::writeRuler(), LatexGenerator::writeRuler(), HtmlGenerator::writeSearchPage(), RTFGenerator::writeStartAnnoItem(), LatexGenerator::writeStyleSheetFile(), RTFGenerator::writeStyleSheetFile(), ManGenerator::writeSynopsis(), writeTagFile(), ClassDefImpl::writeTagFile(), GroupDefImpl::writeTagFile(), NamespaceDefImpl::writeTagFile(), PageDefImpl::writeTagFile(), MemberDefImpl::writeTagFile(), DirDefImpl::writeTagFile(), FileDefImpl::writeTagFile(), VhdlDocGen::writeTagFile(), writeTemplateArgumentList(), DocSets::writeToken(), HtmlCodeGenerator::writeTooltip(), DotNode::writeXML(), and writeXMLHeader().
operator<<()
FTextStream& operator<< (FTextStream & s, FTSFUNC f) inline
Definition at line 69 of file ftextstream.h.