Doxygen: src/definition.h File Reference
definition.h File Reference
#include <vector>
#include <qlist.h>
#include <qdict.h>
#include "types.h"
#include "reflist.h"
Classes
struct DocInfo
Data associated with a detailed description.
struct BriefInfo
Data associated with a brief description.
struct BodyInfo
Data associated with description found in the body.
class DefinitionIntf
Abstract interface for a Definition or DefinitionList.
class Definition
The common base class of all entity definitions found in the sources.
struct Definition::Cookie
class DefinitionList
A list of Definition objects.
class DefinitionListIterator
An iterator for Definition objects in a DefinitionList.
Functions
bool readCodeFragment (const char *fileName, int &startLine, int &endLine, QCString &result)
Reads a fragment from file fileName starting with line startLine and ending with line endLine.
Function Documentation
readCodeFragment()
bool readCodeFragment (const char * fileName, int & startLine, int & endLine, QCString & result)
Reads a fragment from file fileName starting with line startLine and ending with line endLine.
The result is returned as a string via result. The function returns TRUE if successful and FALSE in case of an error.
Reads a fragment of code from file fileName starting at line startLine and ending at line endLine (inclusive). The fragment is stored in result. If FALSE is returned the code fragment could not be found.
The file is scanned for a opening bracket ('{') from startLine onward The line actually containing the bracket is returned via startLine. The file is scanned for a closing bracket ('}') from endLine backward. The line actually containing the bracket is returned via endLine. Note that for VHDL code the bracket search is not done.
Definition at line 839 of file definition.cpp.
References Config_getBool, Config_getInt, BufStr::data(), Debug::FilterOutput, g_filterCache, FilterCache::getFileContents(), getFileFilter(), getLanguageFromFileName(), Debug::print(), SrcLangExt_Fortran, SrcLangExt_Python, SrcLangExt_VHDL, and transcodeCharacterStringToUTF8().
Referenced by VhdlDocGen::createFlowChart(), MemberContext::Private::sourceCode(), and DefinitionImpl::writeInlineCode().